// Слова диалога переводов. Ко-локированы рядом с ним: это строки интерфейса,
// то есть данные, известные на сборке. Ср. GLOSSARY.md, «три вида переводов».

export type TranslationsUi = {
  title: string
  intro: string
  translateAll: string
  translateField: string
  translating: string
  save: string
  saving: string
  skip: string
  close: string
  empty: string
  /** Текст у вопросика — почему пропуск это нормально. */
  hint: string
  failed: string
  saved: string
}

const UI: Record<string, TranslationsUi> = {
  en: { title: 'Add translations', intro: 'Fill the languages your app ships in. Nothing is translated until you ask.', translateAll: 'Translate everything', translateField: 'Translate this field', translating: 'Translating…', save: 'Save translations', saving: 'Saving…', skip: 'Skip for now', close: 'Close', empty: 'Empty until you press translate', hint: 'Designing a page and not sure it is final? Skip the translations. The record lives in the language you are working in, and you add the rest when the wording settles — translating a draft spends time and tokens on text you are about to rewrite.', failed: 'Could not do that', saved: 'Translations saved' },
  ru: { title: 'Добавление переводов', intro: 'Заполните языки, на которых работает приложение. Ничего не переводится, пока вы не попросите.', translateAll: 'Перевести всё', translateField: 'Перевести это поле', translating: 'Перевожу…', save: 'Сохранить переводы', saving: 'Сохраняю…', skip: 'Пропустить', close: 'Закрыть', empty: 'Пусто, пока не нажат перевод', hint: 'Проектируете страницу и не уверены, что это финальная редакция? Пропустите переводы. Запись останется на языке, на котором вы работаете, а остальные добавите, когда формулировки устоятся, — перевод черновика тратит время и токены на текст, который вы вот-вот перепишете.', failed: 'Не удалось', saved: 'Переводы сохранены' },
  es: { title: 'Añadir traducciones', intro: 'Rellena los idiomas de tu aplicación. Nada se traduce hasta que lo pidas.', translateAll: 'Traducir todo', translateField: 'Traducir este campo', translating: 'Traduciendo…', save: 'Guardar traducciones', saving: 'Guardando…', skip: 'Omitir por ahora', close: 'Cerrar', empty: 'Vacío hasta que pulses traducir', hint: '¿Estás diseñando y no sabes si es la versión final? Omite las traducciones. El registro vive en el idioma en el que trabajas y añades el resto cuando el texto se asiente: traducir un borrador gasta tiempo y tokens en algo que vas a reescribir.', failed: 'No se pudo', saved: 'Traducciones guardadas' },
  fr: { title: 'Ajouter des traductions', intro: 'Remplissez les langues de votre application. Rien n’est traduit tant que vous ne le demandez pas.', translateAll: 'Tout traduire', translateField: 'Traduire ce champ', translating: 'Traduction…', save: 'Enregistrer les traductions', saving: 'Enregistrement…', skip: 'Passer pour l’instant', close: 'Fermer', empty: 'Vide jusqu’à la traduction', hint: 'Vous concevez une page sans savoir si elle est finale ? Passez les traductions. L’enregistrement reste dans votre langue de travail, et vous ajouterez le reste une fois le texte stabilisé — traduire un brouillon dépense du temps et des tokens pour du texte que vous allez réécrire.', failed: 'Échec', saved: 'Traductions enregistrées' },
  it: { title: 'Aggiungi traduzioni', intro: 'Compila le lingue della tua applicazione. Nulla viene tradotto finché non lo chiedi.', translateAll: 'Traduci tutto', translateField: 'Traduci questo campo', translating: 'Traduzione…', save: 'Salva traduzioni', saving: 'Salvataggio…', skip: 'Salta per ora', close: 'Chiudi', empty: 'Vuoto finché non traduci', hint: 'Stai progettando e non sai se è la versione finale? Salta le traduzioni. Il record resta nella lingua in cui lavori e aggiungi il resto quando il testo si assesta: tradurre una bozza spende tempo e token su testo che riscriverai.', failed: 'Operazione non riuscita', saved: 'Traduzioni salvate' },
  de: { title: 'Übersetzungen hinzufügen', intro: 'Füllen Sie die Sprachen Ihrer Anwendung. Es wird nichts übersetzt, bevor Sie darum bitten.', translateAll: 'Alles übersetzen', translateField: 'Dieses Feld übersetzen', translating: 'Übersetze…', save: 'Übersetzungen speichern', saving: 'Speichere…', skip: 'Vorerst überspringen', close: 'Schließen', empty: 'Leer, bis Sie übersetzen', hint: 'Entwerfen Sie noch und wissen nicht, ob es die finale Fassung ist? Überspringen Sie die Übersetzungen. Der Eintrag bleibt in Ihrer Arbeitssprache; den Rest fügen Sie hinzu, wenn der Text steht — einen Entwurf zu übersetzen kostet Zeit und Tokens für Text, den Sie ohnehin neu schreiben.', failed: 'Fehlgeschlagen', saved: 'Übersetzungen gespeichert' },
  pt: { title: 'Adicionar traduções', intro: 'Preencha os idiomas do seu aplicativo. Nada é traduzido até você pedir.', translateAll: 'Traduzir tudo', translateField: 'Traduzir este campo', translating: 'Traduzindo…', save: 'Salvar traduções', saving: 'Salvando…', skip: 'Pular por agora', close: 'Fechar', empty: 'Vazio até você traduzir', hint: 'Está desenhando e não sabe se é a versão final? Pule as traduções. O registro fica no idioma em que você trabalha e o resto vem quando o texto assentar — traduzir rascunho gasta tempo e tokens com texto que você vai reescrever.', failed: 'Não foi possível', saved: 'Traduções salvas' },
  pl: { title: 'Dodaj tłumaczenia', intro: 'Wypełnij języki swojej aplikacji. Nic nie jest tłumaczone, dopóki nie poprosisz.', translateAll: 'Przetłumacz wszystko', translateField: 'Przetłumacz to pole', translating: 'Tłumaczę…', save: 'Zapisz tłumaczenia', saving: 'Zapisuję…', skip: 'Pomiń na razie', close: 'Zamknij', empty: 'Pusto, dopóki nie przetłumaczysz', hint: 'Projektujesz i nie wiesz, czy to wersja finalna? Pomiń tłumaczenia. Wpis zostaje w języku, w którym pracujesz, a resztę dodasz, gdy tekst się ustali — tłumaczenie szkicu to czas i tokeny wydane na tekst, który i tak przepiszesz.', failed: 'Nie udało się', saved: 'Tłumaczenia zapisane' },
  tr: { title: 'Çeviri ekle', intro: 'Uygulamanızın dillerini doldurun. Siz istemeden hiçbir şey çevrilmez.', translateAll: 'Hepsini çevir', translateField: 'Bu alanı çevir', translating: 'Çevriliyor…', save: 'Çevirileri kaydet', saving: 'Kaydediliyor…', skip: 'Şimdilik atla', close: 'Kapat', empty: 'Çevirene kadar boş', hint: 'Sayfayı tasarlıyorsunuz ve son hâli mi bilmiyor musunuz? Çevirileri atlayın. Kayıt çalıştığınız dilde kalır, metin oturunca gerisini eklersiniz — taslağı çevirmek, birazdan yeniden yazacağınız metne zaman ve token harcamaktır.', failed: 'Başarısız', saved: 'Çeviriler kaydedildi' },
  nl: { title: 'Vertalingen toevoegen', intro: 'Vul de talen van uw applicatie in. Er wordt niets vertaald tot u erom vraagt.', translateAll: 'Alles vertalen', translateField: 'Dit veld vertalen', translating: 'Bezig met vertalen…', save: 'Vertalingen opslaan', saving: 'Opslaan…', skip: 'Nu overslaan', close: 'Sluiten', empty: 'Leeg tot u vertaalt', hint: 'Ontwerpt u nog en weet u niet of dit de definitieve versie is? Sla de vertalingen over. De record blijft in uw werktaal en de rest voegt u toe zodra de tekst vastligt — een concept vertalen kost tijd en tokens voor tekst die u toch herschrijft.', failed: 'Niet gelukt', saved: 'Vertalingen opgeslagen' },
}

export function translationsUi(lang: string): TranslationsUi {
  return UI[lang] ?? UI[lang.slice(0, 2)] ?? UI.en
}
