// Слова диалога переводов. Ко-локированы рядом с ним: это строки интерфейса,
// то есть данные, известные на сборке. Ср. GLOSSARY.md, «три вида переводов».

export type TranslationsUi = {
  title: string
  intro: string
  translateTab: string
  translateAllTabs: string
  translating: string
  saveOne: string
  saving: string
  savedMark: string
  /** Причины отказа — по коду двери перевода. */
  errNoKey: string
  errBadKey: string
  errNoFunds: string
  errRateLimit: string
  errUpstream: string
  errKeyLink: string
  errFundsLink: string
  skip: string
  close: string
  empty: string
  /** Текст у вопросика — почему пропуск это нормально. */
  hint: string
  failed: string
  saved: string
}

const UI: Record<string, TranslationsUi> = {
  en: { title: 'Add translations', intro: 'Fill the languages your app ships in. Nothing is translated until you ask.', translateTab: 'Translate this tab', translateAllTabs: 'Translate all tabs', saveOne: 'Save this translation', savedMark: 'saved', errNoKey: 'No OpenAI key. Translation and voice input both draw on it — add the key in the control panel.', errBadKey: 'OpenAI rejected the key. Check it in the control panel: it may have been revoked or copied incompletely.', errNoFunds: 'Not enough funds on the OpenAI balance. Top it up and try again — you are charged only for what is used.', errRateLimit: 'OpenAI is limiting the request rate. Wait a few seconds and try again.', errUpstream: 'OpenAI did not answer. Try again in a moment.', errKeyLink: 'Open OpenAI settings in the control panel', errFundsLink: 'Open OpenAI billing', translating: 'Translating…', saving: 'Saving…', skip: 'Skip for now', close: 'Close', empty: 'Empty until you press translate', hint: 'Designing a page and not sure it is final? Skip the translations. The record lives in the language you are working in, and you add the rest when the wording settles — translating a draft spends time and tokens on text you are about to rewrite.', failed: 'Could not do that', saved: 'Translations saved' },
  ru: { title: 'Добавление переводов', intro: 'Заполните языки, на которых работает приложение. Ничего не переводится, пока вы не попросите.', translateTab: 'Перевести эту вкладку', translateAllTabs: 'Перевести все вкладки', saveOne: 'Сохранить перевод', savedMark: 'сохранено', errNoKey: 'Нет ключа OpenAI. Из него платят и перевод, и голосовой ввод — добавьте ключ в панели управления.', errBadKey: 'OpenAI отклонил ключ. Проверьте его в панели управления: он мог быть отозван или скопирован не полностью.', errNoFunds: 'Недостаточно средств на балансе OpenAI. Пополните его и повторите — списывается только за использованное.', errRateLimit: 'OpenAI ограничивает частоту запросов. Подождите несколько секунд и повторите.', errUpstream: 'OpenAI не ответил. Повторите через мгновение.', errKeyLink: 'Открыть настройки OpenAI в панели', errFundsLink: 'Открыть баланс OpenAI', translating: 'Перевожу…', saving: 'Сохраняю…', skip: 'Пропустить', close: 'Закрыть', empty: 'Пусто, пока не нажат перевод', hint: 'Проектируете страницу и не уверены, что это финальная редакция? Пропустите переводы. Запись останется на языке, на котором вы работаете, а остальные добавите, когда формулировки устоятся, — перевод черновика тратит время и токены на текст, который вы вот-вот перепишете.', failed: 'Не удалось', saved: 'Переводы сохранены' },
  es: { title: 'Añadir traducciones', intro: 'Rellena los idiomas de tu aplicación. Nada se traduce hasta que lo pidas.', translateTab: 'Traducir esta pestaña', translateAllTabs: 'Traducir todas las pestañas', saveOne: 'Guardar traducción', savedMark: 'guardado', errNoKey: 'No hay clave de OpenAI. De ella pagan la traducción y la voz: añádela en el panel de control.', errBadKey: 'OpenAI rechazó la clave. Revísala en el panel: puede estar revocada o copiada a medias.', errNoFunds: 'Saldo insuficiente en OpenAI. Recárgalo e inténtalo de nuevo: solo se cobra lo usado.', errRateLimit: 'OpenAI está limitando las peticiones. Espera unos segundos e inténtalo de nuevo.', errUpstream: 'OpenAI no respondió. Inténtalo de nuevo en un momento.', errKeyLink: 'Abrir ajustes de OpenAI en el panel', errFundsLink: 'Abrir facturación de OpenAI', translating: 'Traduciendo…', saving: 'Guardando…', skip: 'Omitir por ahora', close: 'Cerrar', empty: 'Vacío hasta que pulses traducir', hint: '¿Estás diseñando y no sabes si es la versión final? Omite las traducciones. El registro vive en el idioma en el que trabajas y añades el resto cuando el texto se asiente: traducir un borrador gasta tiempo y tokens en algo que vas a reescribir.', failed: 'No se pudo', saved: 'Traducciones guardadas' },
  fr: { title: 'Ajouter des traductions', intro: 'Remplissez les langues de votre application. Rien n’est traduit tant que vous ne le demandez pas.', translateTab: 'Traduire cet onglet', translateAllTabs: 'Traduire tous les onglets', saveOne: 'Enregistrer la traduction', savedMark: 'enregistré', errNoKey: 'Aucune clé OpenAI. La traduction et la saisie vocale en dépendent — ajoutez-la dans le panneau.', errBadKey: 'OpenAI a refusé la clé. Vérifiez-la dans le panneau : révoquée ou copiée partiellement.', errNoFunds: 'Solde OpenAI insuffisant. Rechargez et réessayez — vous ne payez que ce qui est utilisé.', errRateLimit: 'OpenAI limite le rythme des requêtes. Patientez quelques secondes.', errUpstream: 'OpenAI n’a pas répondu. Réessayez dans un instant.', errKeyLink: 'Ouvrir les réglages OpenAI dans le panneau', errFundsLink: 'Ouvrir la facturation OpenAI', translating: 'Traduction…', saving: 'Enregistrement…', skip: 'Passer pour l’instant', close: 'Fermer', empty: 'Vide jusqu’à la traduction', hint: 'Vous concevez une page sans savoir si elle est finale ? Passez les traductions. L’enregistrement reste dans votre langue de travail, et vous ajouterez le reste une fois le texte stabilisé — traduire un brouillon dépense du temps et des tokens pour du texte que vous allez réécrire.', failed: 'Échec', saved: 'Traductions enregistrées' },
  it: { title: 'Aggiungi traduzioni', intro: 'Compila le lingue della tua applicazione. Nulla viene tradotto finché non lo chiedi.', translateTab: 'Traduci questa scheda', translateAllTabs: 'Traduci tutte le schede', saveOne: 'Salva traduzione', savedMark: 'salvato', errNoKey: 'Manca la chiave OpenAI. Traduzione e voce la usano: aggiungila nel pannello di controllo.', errBadKey: 'OpenAI ha rifiutato la chiave. Controllala nel pannello: revocata o copiata a metà.', errNoFunds: 'Credito OpenAI insufficiente. Ricarica e riprova: paghi solo ciò che usi.', errRateLimit: 'OpenAI sta limitando le richieste. Attendi qualche secondo e riprova.', errUpstream: 'OpenAI non ha risposto. Riprova tra poco.', errKeyLink: 'Apri le impostazioni OpenAI nel pannello', errFundsLink: 'Apri la fatturazione OpenAI', translating: 'Traduzione…', saving: 'Salvataggio…', skip: 'Salta per ora', close: 'Chiudi', empty: 'Vuoto finché non traduci', hint: 'Stai progettando e non sai se è la versione finale? Salta le traduzioni. Il record resta nella lingua in cui lavori e aggiungi il resto quando il testo si assesta: tradurre una bozza spende tempo e token su testo che riscriverai.', failed: 'Operazione non riuscita', saved: 'Traduzioni salvate' },
  de: { title: 'Übersetzungen hinzufügen', intro: 'Füllen Sie die Sprachen Ihrer Anwendung. Es wird nichts übersetzt, bevor Sie darum bitten.', translateTab: 'Diesen Tab übersetzen', translateAllTabs: 'Alle Tabs übersetzen', saveOne: 'Übersetzung speichern', savedMark: 'gespeichert', errNoKey: 'Kein OpenAI-Schlüssel. Übersetzung und Spracheingabe zahlen daraus — im Panel hinterlegen.', errBadKey: 'OpenAI hat den Schlüssel abgelehnt. Prüfen Sie ihn im Panel: widerrufen oder unvollständig kopiert.', errNoFunds: 'Zu wenig Guthaben bei OpenAI. Laden Sie auf und versuchen Sie es erneut — berechnet wird nur Verbrauchtes.', errRateLimit: 'OpenAI drosselt die Anfragen. Warten Sie ein paar Sekunden.', errUpstream: 'OpenAI hat nicht geantwortet. Bitte gleich erneut versuchen.', errKeyLink: 'OpenAI-Einstellungen im Panel öffnen', errFundsLink: 'OpenAI-Abrechnung öffnen', translating: 'Übersetze…', saving: 'Speichere…', skip: 'Vorerst überspringen', close: 'Schließen', empty: 'Leer, bis Sie übersetzen', hint: 'Entwerfen Sie noch und wissen nicht, ob es die finale Fassung ist? Überspringen Sie die Übersetzungen. Der Eintrag bleibt in Ihrer Arbeitssprache; den Rest fügen Sie hinzu, wenn der Text steht — einen Entwurf zu übersetzen kostet Zeit und Tokens für Text, den Sie ohnehin neu schreiben.', failed: 'Fehlgeschlagen', saved: 'Übersetzungen gespeichert' },
  pt: { title: 'Adicionar traduções', intro: 'Preencha os idiomas do seu aplicativo. Nada é traduzido até você pedir.', translateTab: 'Traduzir esta aba', translateAllTabs: 'Traduzir todas as abas', saveOne: 'Salvar tradução', savedMark: 'salvo', errNoKey: 'Sem chave OpenAI. Tradução e voz pagam dela — adicione no painel de controle.', errBadKey: 'A OpenAI recusou a chave. Verifique no painel: revogada ou copiada pela metade.', errNoFunds: 'Saldo insuficiente na OpenAI. Recarregue e tente de novo — cobra-se apenas o usado.', errRateLimit: 'A OpenAI está limitando as requisições. Aguarde alguns segundos.', errUpstream: 'A OpenAI não respondeu. Tente de novo em instantes.', errKeyLink: 'Abrir configurações da OpenAI no painel', errFundsLink: 'Abrir faturamento da OpenAI', translating: 'Traduzindo…', saving: 'Salvando…', skip: 'Pular por agora', close: 'Fechar', empty: 'Vazio até você traduzir', hint: 'Está desenhando e não sabe se é a versão final? Pule as traduções. O registro fica no idioma em que você trabalha e o resto vem quando o texto assentar — traduzir rascunho gasta tempo e tokens com texto que você vai reescrever.', failed: 'Não foi possível', saved: 'Traduções salvas' },
  pl: { title: 'Dodaj tłumaczenia', intro: 'Wypełnij języki swojej aplikacji. Nic nie jest tłumaczone, dopóki nie poprosisz.', translateTab: 'Przetłumacz tę zakładkę', translateAllTabs: 'Przetłumacz wszystkie zakładki', saveOne: 'Zapisz tłumaczenie', savedMark: 'zapisano', errNoKey: 'Brak klucza OpenAI. Tłumaczenie i głos z niego korzystają — dodaj go w panelu.', errBadKey: 'OpenAI odrzuciło klucz. Sprawdź go w panelu: mógł zostać cofnięty lub skopiowany częściowo.', errNoFunds: 'Za mało środków w OpenAI. Doładuj i spróbuj ponownie — płacisz tylko za zużycie.', errRateLimit: 'OpenAI ogranicza liczbę żądań. Poczekaj kilka sekund.', errUpstream: 'OpenAI nie odpowiedziało. Spróbuj ponownie za chwilę.', errKeyLink: 'Otwórz ustawienia OpenAI w panelu', errFundsLink: 'Otwórz rozliczenia OpenAI', translating: 'Tłumaczę…', saving: 'Zapisuję…', skip: 'Pomiń na razie', close: 'Zamknij', empty: 'Pusto, dopóki nie przetłumaczysz', hint: 'Projektujesz i nie wiesz, czy to wersja finalna? Pomiń tłumaczenia. Wpis zostaje w języku, w którym pracujesz, a resztę dodasz, gdy tekst się ustali — tłumaczenie szkicu to czas i tokeny wydane na tekst, który i tak przepiszesz.', failed: 'Nie udało się', saved: 'Tłumaczenia zapisane' },
  tr: { title: 'Çeviri ekle', intro: 'Uygulamanızın dillerini doldurun. Siz istemeden hiçbir şey çevrilmez.', translateTab: 'Bu sekmeyi çevir', translateAllTabs: 'Tüm sekmeleri çevir', saveOne: 'Çeviriyi kaydet', savedMark: 'kaydedildi', errNoKey: 'OpenAI anahtarı yok. Çeviri ve ses girişi ondan ödenir — panelden ekleyin.', errBadKey: 'OpenAI anahtarı reddetti. Panelden kontrol edin: iptal edilmiş ya da eksik kopyalanmış olabilir.', errNoFunds: 'OpenAI bakiyesi yetersiz. Yükleyip tekrar deneyin — yalnızca kullanılan kadar ücretlendirilir.', errRateLimit: 'OpenAI istek hızını sınırlıyor. Birkaç saniye bekleyin.', errUpstream: 'OpenAI yanıt vermedi. Birazdan tekrar deneyin.', errKeyLink: 'Panelde OpenAI ayarlarını aç', errFundsLink: 'OpenAI faturalandırmayı aç', translating: 'Çevriliyor…', saving: 'Kaydediliyor…', skip: 'Şimdilik atla', close: 'Kapat', empty: 'Çevirene kadar boş', hint: 'Sayfayı tasarlıyorsunuz ve son hâli mi bilmiyor musunuz? Çevirileri atlayın. Kayıt çalıştığınız dilde kalır, metin oturunca gerisini eklersiniz — taslağı çevirmek, birazdan yeniden yazacağınız metne zaman ve token harcamaktır.', failed: 'Başarısız', saved: 'Çeviriler kaydedildi' },
  nl: { title: 'Vertalingen toevoegen', intro: 'Vul de talen van uw applicatie in. Er wordt niets vertaald tot u erom vraagt.', translateTab: 'Dit tabblad vertalen', translateAllTabs: 'Alle tabbladen vertalen', saveOne: 'Vertaling opslaan', savedMark: 'opgeslagen', errNoKey: 'Geen OpenAI-sleutel. Vertaling en spraakinvoer betalen eruit — voeg hem toe in het paneel.', errBadKey: 'OpenAI weigerde de sleutel. Controleer hem in het paneel: ingetrokken of half gekopieerd.', errNoFunds: 'Onvoldoende saldo bij OpenAI. Vul aan en probeer opnieuw — u betaalt alleen verbruik.', errRateLimit: 'OpenAI beperkt het aantal verzoeken. Wacht enkele seconden.', errUpstream: 'OpenAI antwoordde niet. Probeer het zo opnieuw.', errKeyLink: 'OpenAI-instellingen in het paneel openen', errFundsLink: 'OpenAI-facturering openen', translating: 'Bezig met vertalen…', saving: 'Opslaan…', skip: 'Nu overslaan', close: 'Sluiten', empty: 'Leeg tot u vertaalt', hint: 'Ontwerpt u nog en weet u niet of dit de definitieve versie is? Sla de vertalingen over. De record blijft in uw werktaal en de rest voegt u toe zodra de tekst vastligt — een concept vertalen kost tijd en tokens voor tekst die u toch herschrijft.', failed: 'Niet gelukt', saved: 'Vertalingen opgeslagen' },
}

export function translationsUi(lang: string): TranslationsUi {
  return UI[lang] ?? UI[lang.slice(0, 2)] ?? UI.en
}
