// Words of the catalogue page. Co-located in `_data` because localized UI
// strings are DATA — the same rule the content tabs follow.
//
// Ten languages, the set the rest of this project ships. Nothing here is
// optional: a string typed straight into JSX is invisible to translation and
// stays English on every other market forever.

export type ProductsUi = {
  /** Заголовок страницы — статический, уезжает в предрендер. */
  title: string
  /** Описание под заголовком — тоже статическое. */
  subtitle: string
  /** Кнопки формы. */
  add: string
  cancelAdd: string
  newProduct: string
  name: string
  price: string
  uploadPhoto: string
  save: string
  /** Тосты. */
  created: string
  deleted: string
  /** Подпись о том, где лежат данные. */
  storageNote: string
  nothingFound: string
  /** Правка полей карточки. */
  edit: string
  saveField: string
  cancelEdit: string
  fieldSaved: string
  baseValue: string
  translation: string
  descriptionField: string
  translations: string
  /** Карточка одного продукта. */
  one: string
  back: string
  notFoundTitle: string
  notFoundBody: string
  errorTitle: string
  errorBody: string
  retry: string
}

const UI: Record<string, ProductsUi> = {
  en: { title: 'Product catalogue', subtitle: 'Create products and add them to the catalogue. Backed by the database and the media service.', add: 'Add product', cancelAdd: 'Cancel', newProduct: 'New product', name: 'Product name', price: 'Price', uploadPhoto: 'Upload photo', save: 'Save', created: 'Product created', deleted: 'Product deleted', storageNote: 'Rows in the database, images in the media service.', nothingFound: 'Nothing matches that search.', edit: 'Edit', saveField: 'Save', cancelEdit: 'Cancel', fieldSaved: 'Saved', baseValue: 'Base (English)', translation: 'Translation', descriptionField: 'Description', translations: 'Translations', one: 'Product', back: 'Back to the catalogue', notFoundTitle: 'No such product', notFoundBody: 'It was deleted, or the address is wrong.', errorTitle: 'Something broke on this page', errorBody: 'The catalogue itself is fine — this screen failed. Try again.', retry: 'Try again' },
  fr: { title: 'Catalogue de produits', subtitle: 'Créez des produits et ajoutez-les au catalogue. Adossé à la base de données et au service média.', add: 'Ajouter un produit', cancelAdd: 'Annuler', newProduct: 'Nouveau produit', name: 'Nom', price: 'Prix', uploadPhoto: 'Téléverser une photo', save: 'Enregistrer', created: 'Produit créé', deleted: 'Produit supprimé', storageNote: 'Lignes en base, images dans le service média.', nothingFound: 'Aucun résultat pour cette recherche.', edit: 'Modifier', saveField: 'Enregistrer', cancelEdit: 'Annuler', fieldSaved: 'Enregistré', baseValue: 'Base (anglais)', translation: 'Traduction', descriptionField: 'Description', translations: 'Traductions', one: 'Produit', back: 'Retour au catalogue', notFoundTitle: 'Ce produit n’existe pas', notFoundBody: 'Il a été supprimé ou l’adresse est erronée.', errorTitle: 'Quelque chose a cassé sur cette page', errorBody: 'Le catalogue va bien — cet écran a échoué. Réessayez.', retry: 'Réessayer' },
  es: { title: 'Catálogo de productos', subtitle: 'Crea productos y añádelos al catálogo. Respaldado por la base de datos y el servicio de medios.', add: 'Añadir producto', cancelAdd: 'Cancelar', newProduct: 'Nuevo producto', name: 'Nombre', price: 'Precio', uploadPhoto: 'Subir foto', save: 'Guardar', created: 'Producto creado', deleted: 'Producto eliminado', storageNote: 'Filas en la base de datos, imágenes en el servicio de medios.', nothingFound: 'No hay resultados para esa búsqueda.', edit: 'Editar', saveField: 'Guardar', cancelEdit: 'Cancelar', fieldSaved: 'Guardado', baseValue: 'Base (inglés)', translation: 'Traducción', descriptionField: 'Descripción', translations: 'Traducciones', one: 'Producto', back: 'Volver al catálogo', notFoundTitle: 'No existe ese producto', notFoundBody: 'Fue eliminado o la dirección es incorrecta.', errorTitle: 'Algo se rompió en esta página', errorBody: 'El catálogo está bien; falló esta pantalla. Inténtalo de nuevo.', retry: 'Reintentar' },
  pt: { title: 'Catálogo de produtos', subtitle: 'Crie produtos e adicione-os ao catálogo. Apoiado no banco de dados e no serviço de mídia.', add: 'Adicionar produto', cancelAdd: 'Cancelar', newProduct: 'Novo produto', name: 'Nome', price: 'Preço', uploadPhoto: 'Enviar foto', save: 'Salvar', created: 'Produto criado', deleted: 'Produto excluído', storageNote: 'Linhas no banco, imagens no serviço de mídia.', nothingFound: 'Nada corresponde a essa busca.', edit: 'Editar', saveField: 'Salvar', cancelEdit: 'Cancelar', fieldSaved: 'Salvo', baseValue: 'Base (inglês)', translation: 'Tradução', descriptionField: 'Descrição', translations: 'Traduções', one: 'Produto', back: 'Voltar ao catálogo', notFoundTitle: 'Esse produto não existe', notFoundBody: 'Foi excluído ou o endereço está errado.', errorTitle: 'Algo quebrou nesta página', errorBody: 'O catálogo está bem — esta tela falhou. Tente de novo.', retry: 'Tentar de novo' },
  de: { title: 'Produktkatalog', subtitle: 'Legen Sie Produkte an und fügen Sie sie dem Katalog hinzu. Gestützt auf Datenbank und Medien-Dienst.', add: 'Produkt hinzufügen', cancelAdd: 'Abbrechen', newProduct: 'Neues Produkt', name: 'Name', price: 'Preis', uploadPhoto: 'Foto hochladen', save: 'Speichern', created: 'Produkt erstellt', deleted: 'Produkt gelöscht', storageNote: 'Zeilen in der Datenbank, Bilder im Medien-Dienst.', nothingFound: 'Keine Treffer für diese Suche.', edit: 'Bearbeiten', saveField: 'Speichern', cancelEdit: 'Abbrechen', fieldSaved: 'Gespeichert', baseValue: 'Basis (Englisch)', translation: 'Übersetzung', descriptionField: 'Beschreibung', translations: 'Übersetzungen', one: 'Produkt', back: 'Zurück zum Katalog', notFoundTitle: 'Dieses Produkt gibt es nicht', notFoundBody: 'Es wurde gelöscht, oder die Adresse stimmt nicht.', errorTitle: 'Auf dieser Seite ist etwas kaputtgegangen', errorBody: 'Der Katalog ist in Ordnung — dieser Bildschirm nicht. Versuchen Sie es erneut.', retry: 'Erneut versuchen' },
  it: { title: 'Catalogo prodotti', subtitle: 'Crea prodotti e aggiungili al catalogo. Basato sul database e sul servizio media.', add: 'Aggiungi prodotto', cancelAdd: 'Annulla', newProduct: 'Nuovo prodotto', name: 'Nome', price: 'Prezzo', uploadPhoto: 'Carica foto', save: 'Salva', created: 'Prodotto creato', deleted: 'Prodotto eliminato', storageNote: 'Righe nel database, immagini nel servizio media.', nothingFound: 'Nessun risultato per questa ricerca.', edit: 'Modifica', saveField: 'Salva', cancelEdit: 'Annulla', fieldSaved: 'Salvato', baseValue: 'Base (inglese)', translation: 'Traduzione', descriptionField: 'Descrizione', translations: 'Traduzioni', one: 'Prodotto', back: 'Torna al catalogo', notFoundTitle: 'Questo prodotto non esiste', notFoundBody: 'È stato eliminato o l’indirizzo è errato.', errorTitle: 'Qualcosa si è rotto in questa pagina', errorBody: 'Il catalogo è a posto: è fallita questa schermata. Riprova.', retry: 'Riprova' },
  nl: { title: 'Productcatalogus', subtitle: 'Maak producten aan en voeg ze toe aan de catalogus. Ondersteund door de database en de mediadienst.', add: 'Product toevoegen', cancelAdd: 'Annuleren', newProduct: 'Nieuw product', name: 'Naam', price: 'Prijs', uploadPhoto: 'Foto uploaden', save: 'Opslaan', created: 'Product aangemaakt', deleted: 'Product verwijderd', storageNote: 'Rijen in de database, afbeeldingen in de mediadienst.', nothingFound: 'Geen resultaten voor die zoekopdracht.', edit: 'Bewerken', saveField: 'Opslaan', cancelEdit: 'Annuleren', fieldSaved: 'Opgeslagen', baseValue: 'Basis (Engels)', translation: 'Vertaling', descriptionField: 'Omschrijving', translations: 'Vertalingen', one: 'Product', back: 'Terug naar de catalogus', notFoundTitle: 'Dit product bestaat niet', notFoundBody: 'Het is verwijderd, of het adres klopt niet.', errorTitle: 'Er ging iets stuk op deze pagina', errorBody: 'De catalogus is in orde — dit scherm faalde. Probeer het opnieuw.', retry: 'Opnieuw proberen' },
  sv: { title: 'Produktkatalog', subtitle: 'Skapa produkter och lägg till dem i katalogen. Stöds av databasen och mediatjänsten.', add: 'Lägg till produkt', cancelAdd: 'Avbryt', newProduct: 'Ny produkt', name: 'Produktnamn', price: 'Pris', uploadPhoto: 'Ladda upp foto', save: 'Spara', created: 'Produkt skapad', deleted: 'Produkt borttagen', storageNote: 'Rader i databasen, bilder i mediatjänsten.', nothingFound: 'Inget matchar den sökningen.', edit: 'Redigera', saveField: 'Spara', cancelEdit: 'Avbryt', fieldSaved: 'Sparat', baseValue: 'Bas (engelska)', translation: 'Översättning', descriptionField: 'Beskrivning', translations: 'Översättningar', one: 'Produkt', back: 'Tillbaka till katalogen', notFoundTitle: 'Ingen sådan produkt', notFoundBody: 'Den togs bort, eller så är adressen fel.', errorTitle: 'Något gick sönder på den här sidan', errorBody: 'Katalogen i sig är okej — den här skärmen misslyckades. Försök igen.', retry: 'Försök igen' },
  no: { title: 'Produktkatalog', subtitle: 'Opprett produkter og legg dem til i katalogen. Støttet av databasen og medietjenesten.', add: 'Legg til produkt', cancelAdd: 'Avbryt', newProduct: 'Nytt produkt', name: 'Produktnavn', price: 'Pris', uploadPhoto: 'Last opp bilde', save: 'Lagre', created: 'Produkt opprettet', deleted: 'Produkt slettet', storageNote: 'Rader i databasen, bilder i medietjenesten.', nothingFound: 'Ingenting samsvarer med det søket.', edit: 'Rediger', saveField: 'Lagre', cancelEdit: 'Avbryt', fieldSaved: 'Lagret', baseValue: 'Grunnleggende (engelsk)', translation: 'Oversettelse', descriptionField: 'Beskrivelse', translations: 'Oversettelser', one: 'Produkt', back: 'Tilbake til katalogen', notFoundTitle: 'Produktet finnes ikke', notFoundBody: 'Det ble slettet, eller adressen er feil.', errorTitle: 'Noe gikk galt på denne siden', errorBody: 'Katalogen selv er i orden — denne skjermen feilet. Prøv igjen.', retry: 'Prøv igjen' },
  da: { title: 'Produktkatalog', subtitle: 'Opret produkter, og føj dem til kataloget. Understøttet af databasen og medietjenesten.', add: 'Tilføj produkt', cancelAdd: 'Annuller', newProduct: 'Nyt produkt', name: 'Produktnavn', price: 'Pris', uploadPhoto: 'Upload foto', save: 'Gem', created: 'Produkt oprettet', deleted: 'Produkt slettet', storageNote: 'Rækker i databasen, billeder i medietjenesten.', nothingFound: 'Intet matcher den søgning.', edit: 'Rediger', saveField: 'Gem', cancelEdit: 'Annuller', fieldSaved: 'Gemt', baseValue: 'Basis (engelsk)', translation: 'Oversættelse', descriptionField: 'Beskrivelse', translations: 'Oversættelser', one: 'Produkt', back: 'Tilbage til kataloget', notFoundTitle: 'Intet sådant produkt', notFoundBody: 'Det blev slettet, eller adressen er forkert.', errorTitle: 'Noget gik i stykker på denne side', errorBody: 'Selve kataloget er fint — denne skærm fejlede. Prøv igen.', retry: 'Prøv igen' },
  fi: { title: 'Tuoteluettelo', subtitle: 'Luo tuotteita ja lisää ne luetteloon. Tukena tietokanta ja mediapalvelu.', add: 'Lisää tuote', cancelAdd: 'Peruuta', newProduct: 'Uusi tuote', name: 'Tuotteen nimi', price: 'Hinta', uploadPhoto: 'Lataa kuva', save: 'Tallenna', created: 'Tuote luotu', deleted: 'Tuote poistettu', storageNote: 'Rivit tietokannassa, kuvat mediapalvelussa.', nothingFound: 'Haku ei löytänyt mitään.', edit: 'Muokkaa', saveField: 'Tallenna', cancelEdit: 'Peruuta', fieldSaved: 'Tallennettu', baseValue: 'Perusta (englanti)', translation: 'Käännös', descriptionField: 'Kuvaus', translations: 'Käännökset', one: 'Tuote', back: 'Takaisin luetteloon', notFoundTitle: 'Tuotetta ei löydy', notFoundBody: 'Se poistettiin, tai osoite on väärä.', errorTitle: 'Tällä sivulla tapahtui virhe', errorBody: 'Luettelo itsessään on kunnossa — tämä näyttö epäonnistui. Yritä uudelleen.', retry: 'Yritä uudelleen' },
  is: { title: 'Vörulisti', subtitle: 'Búðu til vörur og bættu þeim í listann. Byggt á gagnagrunni og efnisþjónustu.', add: 'Bæta við vöru', cancelAdd: 'Hætta við', newProduct: 'Ný vara', name: 'Vöruheiti', price: 'Verð', uploadPhoto: 'Hlaða upp mynd', save: 'Vista', created: 'Vara búin til', deleted: 'Vöru eytt', storageNote: 'Færslur í gagnagrunni, myndir í efnisþjónustu.', nothingFound: 'Ekkert passar við þessa leit.', edit: 'Breyta', saveField: 'Vista', cancelEdit: 'Hætta við', fieldSaved: 'Vistað', baseValue: 'Grunngildi (enska)', translation: 'Þýðing', descriptionField: 'Lýsing', translations: 'Þýðingar', one: 'Vara', back: 'Til baka í vörulistann', notFoundTitle: 'Engin slík vara', notFoundBody: 'Henni var eytt, eða vistfangið er rangt.', errorTitle: 'Eitthvað bilaði á þessari síðu', errorBody: 'Vörulistinn sjálfur er í lagi — þessi skjár brást. Reyndu aftur.', retry: 'Reyna aftur' },
  el: { title: 'Κατάλογος προϊόντων', subtitle: 'Δημιουργήστε προϊόντα και προσθέστε τα στον κατάλογο. Υποστηρίζεται από τη βάση δεδομένων και την υπηρεσία πολυμέσων.', add: 'Προσθήκη προϊόντος', cancelAdd: 'Ακύρωση', newProduct: 'Νέο προϊόν', name: 'Όνομα προϊόντος', price: 'Τιμή', uploadPhoto: 'Μεταφόρτωση φωτογραφίας', save: 'Αποθήκευση', created: 'Το προϊόν δημιουργήθηκε', deleted: 'Το προϊόν διαγράφηκε', storageNote: 'Εγγραφές στη βάση δεδομένων, εικόνες στην υπηρεσία πολυμέσων.', nothingFound: 'Δεν βρέθηκε τίποτα για αυτήν την αναζήτηση.', edit: 'Επεξεργασία', saveField: 'Αποθήκευση', cancelEdit: 'Ακύρωση', fieldSaved: 'Αποθηκεύτηκε', baseValue: 'Βάση (Αγγλικά)', translation: 'Μετάφραση', descriptionField: 'Περιγραφή', translations: 'Μεταφράσεις', one: 'Προϊόν', back: 'Επιστροφή στον κατάλογο', notFoundTitle: 'Δεν υπάρχει τέτοιο προϊόν', notFoundBody: 'Διαγράφηκε, ή η διεύθυνση είναι λανθασμένη.', errorTitle: 'Κάτι χάλασε σε αυτήν τη σελίδα', errorBody: 'Ο ίδιος ο κατάλογος είναι εντάξει — απέτυχε αυτή η οθόνη. Δοκιμάστε ξανά.', retry: 'Δοκιμάστε ξανά' },
  pl: { title: 'Katalog produktów', subtitle: 'Twórz produkty i dodawaj je do katalogu. Oparte na bazie danych i usłudze mediów.', add: 'Dodaj produkt', cancelAdd: 'Anuluj', newProduct: 'Nowy produkt', name: 'Nazwa', price: 'Cena', uploadPhoto: 'Prześlij zdjęcie', save: 'Zapisz', created: 'Produkt utworzony', deleted: 'Produkt usunięty', storageNote: 'Wiersze w bazie, obrazy w usłudze mediów.', nothingFound: 'Brak wyników dla tego zapytania.', edit: 'Edytuj', saveField: 'Zapisz', cancelEdit: 'Anuluj', fieldSaved: 'Zapisano', baseValue: 'Podstawa (angielski)', translation: 'Tłumaczenie', descriptionField: 'Opis', translations: 'Tłumaczenia', one: 'Produkt', back: 'Wróć do katalogu', notFoundTitle: 'Nie ma takiego produktu', notFoundBody: 'Został usunięty albo adres jest błędny.', errorTitle: 'Coś się zepsuło na tej stronie', errorBody: 'Katalog jest sprawny — zawiódł ten ekran. Spróbuj ponownie.', retry: 'Spróbuj ponownie' },
  cs: { title: 'Katalog produktů', subtitle: 'Vytvářejte produkty a přidávejte je do katalogu. Podpora databáze a mediální služby.', add: 'Přidat produkt', cancelAdd: 'Zrušit', newProduct: 'Nový produkt', name: 'Název produktu', price: 'Cena', uploadPhoto: 'Nahrát fotku', save: 'Uložit', created: 'Produkt vytvořen', deleted: 'Produkt smazán', storageNote: 'Řádky v databázi, obrázky v mediální službě.', nothingFound: 'Tomuto hledání nic neodpovídá.', edit: 'Upravit', saveField: 'Uložit', cancelEdit: 'Zrušit', fieldSaved: 'Uloženo', baseValue: 'Základ (angličtina)', translation: 'Překlad', descriptionField: 'Popis', translations: 'Překlady', one: 'Produkt', back: 'Zpět do katalogu', notFoundTitle: 'Takový produkt neexistuje', notFoundBody: 'Byl smazán, nebo je adresa chybná.', errorTitle: 'Na této stránce se něco pokazilo', errorBody: 'Samotný katalog je v pořádku — selhala tato obrazovka. Zkuste to znovu.', retry: 'Zkusit znovu' },
  sk: { title: 'Katalóg produktov', subtitle: 'Vytvárajte produkty a pridávajte ich do katalógu. Podporované databázou a mediálnou službou.', add: 'Pridať produkt', cancelAdd: 'Zrušiť', newProduct: 'Nový produkt', name: 'Názov produktu', price: 'Cena', uploadPhoto: 'Nahrať fotku', save: 'Uložiť', created: 'Produkt vytvorený', deleted: 'Produkt vymazaný', storageNote: 'Riadky v databáze, obrázky v mediálnej službe.', nothingFound: 'Tomuto hľadaniu nič nezodpovedá.', edit: 'Upraviť', saveField: 'Uložiť', cancelEdit: 'Zrušiť', fieldSaved: 'Uložené', baseValue: 'Základ (angličtina)', translation: 'Preklad', descriptionField: 'Popis', translations: 'Preklady', one: 'Produkt', back: 'Späť do katalógu', notFoundTitle: 'Taký produkt neexistuje', notFoundBody: 'Bol vymazaný, alebo je adresa nesprávna.', errorTitle: 'Na tejto stránke sa niečo pokazilo', errorBody: 'Samotný katalóg je v poriadku — zlyhala táto obrazovka. Skúste to znova.', retry: 'Skúsiť znova' },
  hu: { title: 'Termékkatalógus', subtitle: 'Hozzon létre termékeket, és adja hozzá őket a katalógushoz. Az adatbázis és a médiaszolgáltatás támogatja.', add: 'Termék hozzáadása', cancelAdd: 'Mégse', newProduct: 'Új termék', name: 'Termék neve', price: 'Ár', uploadPhoto: 'Fénykép feltöltése', save: 'Mentés', created: 'Termék létrehozva', deleted: 'Termék törölve', storageNote: 'Sorok az adatbázisban, képek a médiaszolgáltatásban.', nothingFound: 'Erre a keresésre nincs találat.', edit: 'Szerkesztés', saveField: 'Mentés', cancelEdit: 'Mégse', fieldSaved: 'Mentve', baseValue: 'Alap (angol)', translation: 'Fordítás', descriptionField: 'Leírás', translations: 'Fordítások', one: 'Termék', back: 'Vissza a katalógushoz', notFoundTitle: 'Nincs ilyen termék', notFoundBody: 'Törölték, vagy a cím hibás.', errorTitle: 'Valami elromlott ezen az oldalon', errorBody: 'Maga a katalógus rendben van — ez a képernyő hibázott. Próbálja újra.', retry: 'Próbálja újra' },
  ro: { title: 'Catalog de produse', subtitle: 'Creați produse și adăugați-le în catalog. Susținut de baza de date și de serviciul media.', add: 'Adaugă produs', cancelAdd: 'Anulează', newProduct: 'Produs nou', name: 'Denumire produs', price: 'Preț', uploadPhoto: 'Încarcă fotografie', save: 'Salvează', created: 'Produs creat', deleted: 'Produs șters', storageNote: 'Rânduri în baza de date, imagini în serviciul media.', nothingFound: 'Nimic nu corespunde acestei căutări.', edit: 'Editează', saveField: 'Salvează', cancelEdit: 'Anulează', fieldSaved: 'Salvat', baseValue: 'Bază (engleză)', translation: 'Traducere', descriptionField: 'Descriere', translations: 'Traduceri', one: 'Produs', back: 'Înapoi la catalog', notFoundTitle: 'Nu există un astfel de produs', notFoundBody: 'A fost șters, sau adresa este greșită.', errorTitle: 'Ceva s-a stricat pe această pagină', errorBody: 'Catalogul în sine este în regulă — acest ecran a eșuat. Încercați din nou.', retry: 'Încearcă din nou' },
  hr: { title: 'Katalog proizvoda', subtitle: 'Izradite proizvode i dodajte ih u katalog. Podržano bazom podataka i medijskom uslugom.', add: 'Dodaj proizvod', cancelAdd: 'Odustani', newProduct: 'Novi proizvod', name: 'Naziv proizvoda', price: 'Cijena', uploadPhoto: 'Učitaj fotografiju', save: 'Spremi', created: 'Proizvod je stvoren', deleted: 'Proizvod je izbrisan', storageNote: 'Redovi u bazi podataka, slike u medijskoj usluzi.', nothingFound: 'Ništa ne odgovara toj pretrazi.', edit: 'Uredi', saveField: 'Spremi', cancelEdit: 'Odustani', fieldSaved: 'Spremljeno', baseValue: 'Osnova (engleski)', translation: 'Prijevod', descriptionField: 'Opis', translations: 'Prijevodi', one: 'Proizvod', back: 'Natrag na katalog', notFoundTitle: 'Takav proizvod ne postoji', notFoundBody: 'Izbrisan je, ili je adresa pogrešna.', errorTitle: 'Nešto se pokvarilo na ovoj stranici', errorBody: 'Sam katalog je u redu — ovaj zaslon nije uspio. Pokušajte ponovno.', retry: 'Pokušaj ponovno' },
  sl: { title: 'Katalog izdelkov', subtitle: 'Ustvarite izdelke in jih dodajte v katalog. Podprto s podatkovno bazo in medijsko storitvijo.', add: 'Dodaj izdelek', cancelAdd: 'Prekliči', newProduct: 'Nov izdelek', name: 'Naziv izdelka', price: 'Cena', uploadPhoto: 'Naloži fotografijo', save: 'Shrani', created: 'Izdelek ustvarjen', deleted: 'Izdelek izbrisan', storageNote: 'Vrstice v podatkovni bazi, slike v medijski storitvi.', nothingFound: 'Nič se ne ujema s tem iskanjem.', edit: 'Uredi', saveField: 'Shrani', cancelEdit: 'Prekliči', fieldSaved: 'Shranjeno', baseValue: 'Osnova (angleščina)', translation: 'Prevod', descriptionField: 'Opis', translations: 'Prevodi', one: 'Izdelek', back: 'Nazaj na katalog', notFoundTitle: 'Takega izdelka ni', notFoundBody: 'Izbrisan je bil, ali pa naslov ni pravilen.', errorTitle: 'Na tej strani se je nekaj pokvarilo', errorBody: 'Sam katalog je v redu — ta zaslon ni uspel. Poskusite znova.', retry: 'Poskusi znova' },
  et: { title: 'Tootekataloog', subtitle: 'Looge tooteid ja lisage need kataloogi. Toetatud andmebaasi ja meediateenuse poolt.', add: 'Lisa toode', cancelAdd: 'Tühista', newProduct: 'Uus toode', name: 'Toote nimi', price: 'Hind', uploadPhoto: 'Laadi foto üles', save: 'Salvesta', created: 'Toode loodud', deleted: 'Toode kustutatud', storageNote: 'Read andmebaasis, pildid meediateenuses.', nothingFound: 'Sellele otsingule ei vasta miski.', edit: 'Muuda', saveField: 'Salvesta', cancelEdit: 'Tühista', fieldSaved: 'Salvestatud', baseValue: 'Alusversioon (inglise)', translation: 'Tõlge', descriptionField: 'Kirjeldus', translations: 'Tõlked', one: 'Toode', back: 'Tagasi kataloogi', notFoundTitle: 'Sellist toodet ei ole', notFoundBody: 'See kustutati või aadress on vale.', errorTitle: 'Sellel lehel läks midagi katki', errorBody: 'Kataloog ise on korras — see ekraan ebaõnnestus. Proovi uuesti.', retry: 'Proovi uuesti' },
  __LV_BLOCK__
  ru: { title: 'Каталог продуктов', subtitle: 'Создавайте продукты и добавляйте их в каталог. Данные — в базе, изображения — в медиа-службе.', add: 'Добавить продукт', cancelAdd: 'Отмена', newProduct: 'Новый продукт', name: 'Название', price: 'Цена', uploadPhoto: 'Загрузить фото', save: 'Сохранить', created: 'Продукт создан', deleted: 'Продукт удалён', storageNote: 'Строки в базе, изображения в медиа-службе.', nothingFound: 'По этому запросу ничего нет.', edit: 'Изменить', saveField: 'Сохранить', cancelEdit: 'Отмена', fieldSaved: 'Сохранено', baseValue: 'Базовое (английский)', translation: 'Перевод', descriptionField: 'Описание', translations: 'Переводы', one: 'Продукт', back: 'Назад в каталог', notFoundTitle: 'Такого продукта нет', notFoundBody: 'Он удалён, либо адрес неверный.', errorTitle: 'На этой странице что-то сломалось', errorBody: 'Сам каталог цел — не отработал этот экран. Попробуйте ещё раз.', retry: 'Повторить' },
  __UK_BLOCK__
  tr: { title: 'Ürün kataloğu', subtitle: 'Ürün oluşturun ve kataloğa ekleyin. Veritabanı ve medya servisiyle desteklenir.', add: 'Ürün ekle', cancelAdd: 'İptal', newProduct: 'Yeni ürün', name: 'Ad', price: 'Fiyat', uploadPhoto: 'Fotoğraf yükle', save: 'Kaydet', created: 'Ürün oluşturuldu', deleted: 'Ürün silindi', storageNote: 'Satırlar veritabanında, görseller medya servisinde.', nothingFound: 'Bu aramaya uyan kayıt yok.', edit: 'Düzenle', saveField: 'Kaydet', cancelEdit: 'İptal', fieldSaved: 'Kaydedildi', baseValue: 'Temel (İngilizce)', translation: 'Çeviri', descriptionField: 'Açıklama', translations: 'Çeviriler', one: 'Ürün', back: 'Kataloğa dön', notFoundTitle: 'Böyle bir ürün yok', notFoundBody: 'Silinmiş ya da adres yanlış.', errorTitle: 'Bu sayfada bir şey bozuldu', errorBody: 'Katalog sağlam — bu ekran hata verdi. Yeniden deneyin.', retry: 'Yeniden dene' },
  __HE_BLOCK__
}

export function productsUi(lang: string): ProductsUi {
  return UI[lang] ?? UI[lang.slice(0, 2)] ?? UI.en
}
