import { journalRunStart, journalRunFinish } from "./journal";

// fractera:workflow os-244071e59531649b — GENERATED by orchestrate-project-by-steps from the
// decomposition graph (step 184, contract R6). This workflow is the EXECUTABLE
// mirror of the diagram in the project page's _data/flow.ts — the two are
// ISOMORPHIC: one "use step" function per non-trigger diagram node, in
// topological order, each under its `// node:<id>` marker. Implement ONLY the
// step BODIES (keep the markers and signatures); a new action = extend the GRAPH
// and re-run the engine — a shadow step outside the diagram is forbidden (what
// is not on the diagram does not exist in the project). Journal open/close are
// engine plumbing — keep them as steps (checkpointed ids never double-insert).
//
// Trigger node(s) of the diagram — not steps; the run route (../run/route.ts)
// and the project's cron queue fire this workflow:
//   • "telegram-cron-trigger" — Cron-триггер: запуск конвейера раз в минуту

export async function runProject(input?: string) {
  "use workflow";

  const journalId = await openRun(input);
  const artifacts: Record<string, unknown> = { input };
  try {
    artifacts["fetch-telegram-updates"] = await fetchTelegramUpdates(artifacts);
    artifacts["deliver-due-reminders"] = await deliverDueReminders(artifacts);
    artifacts["detect-hook"] = await detectHook(artifacts);
    artifacts["summarize-message"] = await summarizeMessage(artifacts);
    artifacts["search-memory-recall"] = await searchMemoryRecall(artifacts);
    artifacts["persist-note-to-db"] = await persistNoteToDb(artifacts);
    artifacts["ingest-note-to-memory"] = await ingestNoteToMemory(artifacts);
    artifacts["reply-in-telegram"] = await replyInTelegram(artifacts);
    // TODO: pass the final artifact's resultTitle/resultUrl once the last step is implemented.
    await closeRun(journalId, { ok: true });
    return { journalId, status: "completed" };
  } catch (e) {
    await closeRun(journalId, {
      ok: false,
      error: e instanceof Error ? e.message : String(e),
    });
    throw e;
  }
}

// Journal steps — write the run into project_cron_runs, the same table the
// queue/results tables of the project page read. Keep them as steps: the id is
// checkpointed, so a replay never double-inserts.

async function openRun(input?: string) {
  "use step";

  const id = crypto.randomUUID();
  journalRunStart(id, input);
  return id;
}

async function closeRun(
  id: string,
  result: { ok: boolean; resultTitle?: string; resultUrl?: string; error?: string },
) {
  "use step";

  journalRunFinish(id, result);
}

// ── Diagram-mirror steps (one per non-trigger node, topological order) ──

// node:fetch-telegram-updates — Получить новые сообщения из Telegram (getUpdates) [action]
async function fetchTelegramUpdates(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  // TODO (diagram node "fetch-telegram-updates"): Реализовать тело шага получения обновлений. (1) Объявить в SCHEMA (app/lib/db/index.ts — новые таблицы ТОЛЬКО в SCHEMA) таблицу telegram_notes_state (key TEXT PRIMARY KEY, value TEXT) для курсора last_update_id. (2) GET https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getUpdates?offset=<last_update_id+1>&timeout=0 — короткий запрос без long-poll (шаг живёт внутри минутного тика). (3) Отфильтровать: только message с текстом; если задан TELEGRAM_ALLOWED_CHAT_ID — отбросить чужие чаты. (4) Продвинуть курсор на максимальный update_id СРАЗУ после чтения (защита от повторной обработки при падении дальше). (5) Вернуть массив {chatId, messageId, text, date}. (6) Если пришёл simulateMessage из run-панели — вернуть его как единственное сообщение с chatId = TELEGRAM_ALLOWED_CHAT_ID, Telegram не опрашивать. Токен НИКОГДА не хардкодить — только env (уже в слот-.env.local, правило 143).
  // In: "cron-тик (пусто) или simulateMessage из run-панели" → Out: "массив новых сообщений {chatId, messageId, text, date}; курсор last_update_id продвинут"
  // - [ ] таблица telegram_notes_state в SCHEMA (key/value, курсор last_update_id)
  // - [ ] getUpdates с offset и фильтром по TELEGRAM_ALLOWED_CHAT_ID
  // - [ ] курсор продвигается до обработки (нет повторов при сбое)
  // - [ ] ветка simulateMessage для теста без Telegram
  void artifacts;
  return null;
}

// node:deliver-due-reminders — Доставить наступившие напоминания (дата-пуш) [action]
async function deliverDueReminders(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  // TODO (diagram node "deliver-due-reminders"): Реализовать доставку напоминаний. (1) SELECT из telegram_notes, где reminder_due <= now И не помечено delivered. (2) Для каждой: POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage в chat_id с текстом «Напоминание: вы просили напомнить, что в <HH:mm> нужно <payload/summary>» (дословно то, что заложил пользователь — правильное поведение из видения владельца). (3) Пометить строку delivered=1 (добавить колонку в SCHEMA-таблицу). (4) Идёт параллельной веткой от триггера — не зависит от прихода новых сообщений. Сбой отправки логировать, не ретраить внутри тика (следующий тик повторит).
  // In: "cron-тик (проверка due на каждом прогоне)" → Out: "{delivered: n, errors[]} — отправленные напоминания"
  // - [ ] SELECT наступивших reminder_due (не delivered)
  // - [ ] sendMessage дословным текстом напоминания
  // - [ ] пометить delivered; колонка delivered в SCHEMA
  void artifacts;
  return null;
}

// node:detect-hook — Распознать хук по первым словам (единая точка входа) [transform]
async function detectHook(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  // TODO (diagram node "detect-hook"): Реализовать распознаватель хука. (1) Прочитать активные хуки из таблицы project_hooks (187) через @/lib/db (нормализованные фразы + action save/remind/recall + projectSlug-владелец). (2) Для каждого сообщения: взять первые ~20 слов, прогнать через дешёвую модель по OPENAI_API_KEY с промптом-классификатором «содержит ли текст один из этих хуков; верни action и projectSlug или ignore» (нормализация регистра, ё/е, лишних пробелов через lib/hooks/normalize.ts шага 187). (3) payload = текст ПОСЛЕ фразы-хука; пустой payload → ignore. (4) Вернуть массив {intent: save|remind|recall|ignore, projectSlug, payload, chatId, messageId, date}. Сообщения без хука → ignore, дальше не идут. Дешёвая модель без тяжёлых инструкций — минимальный расход (тезис токен-эффективности).
  // In: "массив сообщений {chatId, messageId, text, date}" → Out: "массив классифицированных {intent: save|remind|recall|ignore, projectSlug, payload, chatId, messageId, date}"
  // - [ ] чтение активных хуков из project_hooks (187) + normalize.ts
  // - [ ] первые ~20 слов → дешёвая модель → action/projectSlug или ignore
  // - [ ] payload = хвост после фразы; пустой → ignore
  // - [ ] промпт-классификатор компактный (токен-эффективность)
  void artifacts;
  return null;
}

// node:summarize-message — Подробное summary сообщения (дешёвая модель) [action]
async function summarizeMessage(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  // TODO (diagram node "summarize-message"): Реализовать инлайн-summary. Для каждого intent∈{save,remind}: (1) POST к дешёвой модели по OPENAI_API_KEY (тот же ключ, что detect-hook; НЕ отдельный навык — инлайн-вызов) с промптом «сделай сжатое, но полное summary этого сообщения, сохрани ключевые факты и даты». (2) Ограничить длину входа/выхода (токен-экономия). (3) Вернуть {messageId, summary} рядом с исходными полями. Сбой summary НЕ роняет прогон: summary = первые N символов исходного текста (мягкая деградация).
  // In: "классифицированные сообщения intent∈{save,remind} {payload, chatId, messageId, date}" → Out: "те же + {summary} на каждое сообщение"
  // - [ ] инлайн-вызов дешёвой модели (без отдельного навыка)
  // - [ ] лимиты длины вход/выход (токен-экономия)
  // - [ ] сбой → summary = усечённый исходный текст (не падать)
  void artifacts;
  return null;
}

// node:search-memory-recall — Найти ответ по заметкам (LightRAG query) [action]
async function searchMemoryRecall(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  // TODO (diagram node "search-memory-recall"): Реализовать поиск. Для каждого intent=recall: (1) POST /api/rag/query (LightRAG :9621) mode=hybrid, query=payload, заголовок X-Agent-Identity: telegram-notes. (2) Ответ LightRAG — готовый связный текст (retrieval+генерация на стороне памяти; прямой LLM-API из проекта НЕ вызывается — правило «только подписка/место Гермеса»). (3) Пустой результат → честный «по вашим заметкам ничего не нашлось по запросу: <payload>». (4) Сбой query → мягко «память временно недоступна». Вернуть {chatId, answer}.
  // In: "сообщения intent=recall {payload, chatId}" → Out: "ответы {chatId, answer, error?}"
  // - [ ] query mode=hybrid c X-Agent-Identity
  // - [ ] пустой результат → честное «ничего не нашлось»
  // - [ ] сбой → мягкая деградация
  void artifacts;
  return null;
}

// node:persist-note-to-db — Записать заметку/напоминание в БД проекта [action]
async function persistNoteToDb(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  // TODO (diagram node "persist-note-to-db"): Реализовать запись в БД. (1) Объявить в SCHEMA таблицу telegram_notes (id INTEGER PRIMARY KEY AUTOINCREMENT, project_slug TEXT, hook_action TEXT, chat_id TEXT, msg_date INTEGER, reminder_due INTEGER NULL, full_text TEXT, summary TEXT, created_at INTEGER). (2) Для intent=save: reminder_due=NULL (заметка, тип 2). (3) Для intent=remind: извлечь дату/время из payload дешёвой моделью (или из detect-hook); если даты нет — пометить needs_when=true (узел reply попросит «когда?»), строку с reminder_due не создавать пока; если дата есть — reminder_due = unix-время (тип 1, дата-пуш). (4) Вернуть {dbId, intent, reminder_due, needs_when, chatId, summary} — dbId нужен для памяти и ответа. Новые таблицы ТОЛЬКО в SCHEMA (появятся в обеих средах).
  // In: "сообщения intent∈{save,remind} с {summary, payload, chatId, date}" → Out: "{dbId, intent, reminder_due, needs_when, chatId, summary} на каждую запись"
  // - [ ] таблица telegram_notes в SCHEMA (все колонки видения владельца)
  // - [ ] save → reminder_due NULL; remind+дата → reminder_due unix; remind без даты → needs_when
  // - [ ] вернуть dbId (для памяти и ответа)
  void artifacts;
  return null;
}

// node:ingest-note-to-memory — Записать заметку в векторную память (LightRAG) [action]
async function ingestNoteToMemory(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  // TODO (diagram node "ingest-note-to-memory"): Реализовать ingest в память. Для каждой записи из БД (intent∈{save,remind}): (1) сформировать документ форматом: «Проект: telegram-notes | Хук: <action> | Дата: <YYYY-MM-DD HH:mm> | Запись #<dbId> | <полный текст>» (идентификатор БД внутри текста — чтобы ответ мог сослаться на запись). (2) POST /api/rag/ingest (LightRAG :9621 через API рабочего пространства) с заголовком X-Agent-Identity: telegram-notes. (3) Короткий текст — валиден (подтверждено шагом 181). (4) Сбой ingest НЕ роняет прогон: фиксируется в результат, уходит в ответ пользователю.
  // In: "записи БД {dbId, intent, chatId, summary} + полный текст" → Out: "{dbId, chatId, ingestOk, error?} на каждую запись"
  // - [ ] формат документа: проект→хук→дата→#dbId→текст
  // - [ ] ingest с X-Agent-Identity: telegram-notes
  // - [ ] сбой → {ingestOk:false}, прогон не падает
  void artifacts;
  return null;
}

// node:reply-in-telegram — Ответить пользователю в Telegram [action]
async function replyInTelegram(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  // TODO (diagram node "reply-in-telegram"): Реализовать ответ. Собрать исходы: (1) save → «Запомнил: <summary>» при ingestOk, «Не смог сохранить: <error>» при сбое. (2) remind с датой → «Напомню <дата>: <summary>». (3) remind needs_when=true → «Когда напомнить? Ответьте датой/временем» (следующее сообщение пользователя обработается как дата — упрощённо в MVP: пользователь повторит с датой). (4) recall → answer из search-memory-recall. (5) POST sendMessage, parse_mode не задавать (plain text — свободная форма не должна ломаться на Markdown-спецсимволах); текст >4096 резать по границе абзаца. (6) Итог прогона {processed, saved, reminded, answered, errors[]} — это результат для dashboard и таблицы результатов (Layer C).
  // In: "результаты ingest {dbId,chatId,ingestOk,summary}, needs_when, recall {chatId,answer}" → Out: "итог прогона {processed, saved, reminded, answered, errors[]} для dashboard/таблицы"
  // - [ ] save→подтверждение, remind→«напомню»/«когда?», recall→answer
  // - [ ] plain text без parse_mode, резка >4096
  // - [ ] итог прогона {processed,saved,reminded,answered,errors[]}
  void artifacts;
  return null;
}
