import { journalRunStart, journalRunFinish } from "./journal";
import { db } from "@/lib/db";
import { normalizePhrase } from "@/lib/hooks/normalize";

// fractera:workflow os-629d27a2ddcfd5e5 — GENERATED by orchestrate-project-by-steps from the
// decomposition graph (step 184, contract R6; automation ontology 188-R), BODIES implemented by
// Claude Code (step 188, variant B: self-sufficient poller — NO native Hermes gateway, zero Hermes
// runtime load). This workflow is the EXECUTABLE mirror of the diagram in the project page's
// _data/flow.ts — the two are ISOMORPHIC: one "use step" function per non-trigger diagram
// node, in topological order, each under its `// node:<id>` marker. A new Action = extend the
// GRAPH and re-run the engine — a shadow step outside the diagram is forbidden.
//
// Trigger node(s) of the diagram — not steps; the run route (../run/route.ts) and the
// project's cron queue fire this workflow (automation ontology 188-R):
//   • "reception-trigger" — reception wake-up (interim cron; target: always-on long-poll listener)
//   • "reminder-cron-trigger" — the schedule that delivers due reminders
//   • "userbot-reception-trigger" — any-chat MTProto reception (advanced track, Phase 6)

// ── Shared config (self-sufficient: read from the slot's own env, never Hermes) ──
const TG_API = "https://api.telegram.org";
const OPENAI_URL = "https://api.openai.com/v1/chat/completions";
const CHEAP_MODEL = process.env.TELEGRAM_NOTES_MODEL ?? "gpt-4o-mini";
const RAG_URL = (process.env.LIGHTRAG_URL ?? "http://localhost:9621").replace(/\/+$/, "");
const RAG_KEY = process.env.LIGHTRAG_API_KEY ?? "";
const PROJECT_SLUG = "telegram-notes";

type TgMessage = { chatId: string; messageId: number; text: string; date: number };
type Intent = "save" | "remind" | "recall" | "ignore";
type Classified = {
  intent: Intent;
  projectSlug: string | null;
  payload: string;
  chatId: string;
  messageId: number;
  date: number;
};
// hookPhrase = the exact phrase that fired (the ontology trace, 188-R); carried from the
// router (detect-hook) down to persist so every record shows which hook matched.
type Classified2 = Classified & { hookPhrase: string };
type WithSummary = Classified2 & { summary: string };
type Persisted = {
  dbId: number | null;
  intent: Intent;
  reminderDue: number | null;
  needsWhen: boolean;
  chatId: string;
  summary: string;
  payload: string;
};
type Ingested = { dbId: number | null; chatId: string; ingestOk: boolean; summary: string; error?: string };
// recall answers carry the query + the db row id so the reply and the record line up (188-R).
type RecallAnswer = { chatId: string; answer: string; query: string; hookPhrase: string; error?: string };

// ── Small helpers (plain functions — no "use step") ──

function botToken(): string {
  const t = process.env.TELEGRAM_BOT_TOKEN ?? "";
  if (!t) throw new Error("TELEGRAM_BOT_TOKEN is not set in the slot env (rule 143)");
  return t;
}

async function tgSend(chatId: string, text: string): Promise<void> {
  // Telegram caps messages at 4096 chars — split on paragraph/sentence boundaries.
  const chunks: string[] = [];
  let rest = text;
  while (rest.length > 4096) {
    let cut = rest.lastIndexOf("\n", 4096);
    if (cut < 2000) cut = rest.lastIndexOf(". ", 4096);
    if (cut < 2000) cut = 4096;
    chunks.push(rest.slice(0, cut));
    rest = rest.slice(cut);
  }
  chunks.push(rest);
  for (const chunk of chunks) {
    await fetch(`${TG_API}/bot${botToken()}/sendMessage`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      // plain text on purpose — free-form notes must not break on Markdown specials.
      body: JSON.stringify({ chat_id: chatId, text: chunk }),
    }).catch(() => undefined);
  }
}

// One cheap-model chat completion. Returns the assistant text (trimmed) or "" on failure —
// callers degrade gracefully (the automation never dies because the model hiccuped).
async function cheapModel(system: string, user: string, maxTokens = 400): Promise<string> {
  const key = process.env.OPENAI_API_KEY ?? "";
  if (!key) return "";
  try {
    const r = await fetch(OPENAI_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` },
      body: JSON.stringify({
        model: CHEAP_MODEL,
        messages: [
          { role: "system", content: system },
          { role: "user", content: user },
        ],
        temperature: 0,
        max_tokens: maxTokens,
      }),
      signal: AbortSignal.timeout(30_000),
    });
    if (!r.ok) return "";
    const data = (await r.json()) as { choices?: Array<{ message?: { content?: string } }> };
    return (data.choices?.[0]?.message?.content ?? "").trim();
  } catch {
    return "";
  }
}

export async function runProject(input?: string) {
  "use workflow";

  const journalId = await openRun(input);
  const artifacts: Record<string, unknown> = { input };
  try {
    artifacts["fetch-telegram-updates"] = await fetchTelegramUpdates(artifacts);
    artifacts["userbot-fetch-messages"] = await userbotFetchMessages(artifacts);
    artifacts["deliver-due-reminders"] = await deliverDueReminders(artifacts);
    artifacts["detect-hook"] = await detectHook(artifacts);
    artifacts["summarize-message"] = await summarizeMessage(artifacts);
    artifacts["search-memory-recall"] = await searchMemoryRecall(artifacts);
    artifacts["persist-note-to-db"] = await persistNoteToDb(artifacts);
    artifacts["ingest-note-to-memory"] = await ingestNoteToMemory(artifacts);
    const outcome = (await replyInTelegram(artifacts)) as {
      processed: number;
      saved: number;
      reminded: number;
      answered: number;
      errors: string[];
    };
    artifacts["reply-in-telegram"] = outcome;
    const title =
      `processed ${outcome.processed} · saved ${outcome.saved} · reminded ${outcome.reminded} · answered ${outcome.answered}` +
      (outcome.errors.length ? ` · ${outcome.errors.length} error(s)` : "");
    await closeRun(journalId, { ok: true, resultTitle: title });
    return { journalId, status: "completed" };
  } catch (e) {
    await closeRun(journalId, {
      ok: false,
      error: e instanceof Error ? e.message : String(e),
    });
    throw e;
  }
}

// Journal steps — write the run into project_cron_runs, the same table the
// queue/results tables of the project page read.

async function openRun(input?: string) {
  "use step";

  const id = crypto.randomUUID();
  journalRunStart(id, input);
  return id;
}

async function closeRun(
  id: string,
  result: { ok: boolean; resultTitle?: string; resultUrl?: string; error?: string },
) {
  "use step";

  journalRunFinish(id, result);
}

// ── Diagram-mirror steps (one per non-trigger node, topological order) ──

// node:fetch-telegram-updates — Fetch new messages from Telegram (getUpdates) [step]
async function fetchTelegramUpdates(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  const allowedChat = process.env.TELEGRAM_ALLOWED_CHAT_ID ?? "";

  // Run-panel / manual test branch: a simulateMessage string is treated as a single
  // incoming message from the allowed chat — Telegram is NOT polled.
  const sim = typeof artifacts.input === "string" ? (artifacts.input as string).trim() : "";
  if (sim) {
    return [
      { chatId: allowedChat || "0", messageId: 0, text: sim, date: Math.floor(Date.now() / 1000) },
    ] satisfies TgMessage[];
  }

  // Persistent cursor: only fetch updates after the last one we processed.
  const cursorRow = (await db
    .prepare("SELECT value FROM telegram_notes_state WHERE key = 'last_update_id'")
    .get()) as { value?: string } | null;
  const lastUpdateId = cursorRow?.value ? Number(cursorRow.value) : 0;

  const url =
    `${TG_API}/bot${botToken()}/getUpdates?timeout=0` +
    (lastUpdateId ? `&offset=${lastUpdateId + 1}` : "");
  let updates: Array<{ update_id: number; message?: { chat?: { id: number }; message_id: number; text?: string; date: number } }> = [];
  try {
    const r = await fetch(url, { signal: AbortSignal.timeout(20_000) });
    const data = (await r.json()) as { ok: boolean; result?: typeof updates };
    if (data.ok && Array.isArray(data.result)) updates = data.result;
  } catch {
    return [] satisfies TgMessage[];
  }

  const messages: TgMessage[] = [];
  let maxUpdateId = lastUpdateId;
  for (const u of updates) {
    if (u.update_id > maxUpdateId) maxUpdateId = u.update_id;
    const m = u.message;
    if (!m || typeof m.text !== "string" || !m.text.trim()) continue;
    const chatId = String(m.chat?.id ?? "");
    if (allowedChat && chatId !== allowedChat) continue; // personal automation
    messages.push({ chatId, messageId: m.message_id, text: m.text, date: m.date });
  }

  // Advance the cursor IMMEDIATELY after reading — a failure further down the pipeline
  // must not cause the same update to be reprocessed on the next tick.
  if (maxUpdateId > lastUpdateId) {
    await db
      .prepare(
        "INSERT INTO telegram_notes_state (key, value) VALUES ('last_update_id', ?) " +
          "ON CONFLICT(key) DO UPDATE SET value = excluded.value",
      )
      .run(String(maxUpdateId));
  }
  return messages;
}

// node:deliver-due-reminders — Deliver due reminders (date push) [step]
async function deliverDueReminders(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";
  void artifacts;

  const now = Math.floor(Date.now() / 1000);
  const due = (await db
    .prepare(
      "SELECT id, chat_id, reminder_due, full_text, summary FROM telegram_notes " +
        "WHERE reminder_due IS NOT NULL AND reminder_due <= ? AND delivered = 0",
    )
    .all(now)) as Array<{ id: number; chat_id: string; reminder_due: number; full_text: string; summary: string }>;

  const errors: string[] = [];
  let delivered = 0;
  for (const row of due) {
    const when = new Date(row.reminder_due * 1000);
    const hhmm = `${String(when.getHours()).padStart(2, "0")}:${String(when.getMinutes()).padStart(2, "0")}`;
    const what = row.summary || row.full_text;
    try {
      await tgSend(row.chat_id, `Reminder: you asked to be reminded at ${hhmm} to ${what}`);
      await db.prepare("UPDATE telegram_notes SET delivered = 1 WHERE id = ?").run(row.id);
      delivered++;
    } catch (e) {
      errors.push(`reminder ${row.id}: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
  return { delivered, errors };
}

// node:userbot-fetch-messages — Receive any-chat messages (userbot) [step]
// The advanced any-chat track (188-R). Inert until Phase 6 wires the MTProto listener: with
// no API creds it returns [] and never errors. When the Phase-6 substrate listener passes a
// userbot-sourced message via the run input, this normalizes it to the shared message shape.
async function userbotFetchMessages(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";
  void artifacts;

  const configured =
    Boolean(process.env.TELEGRAM_API_ID) &&
    Boolean(process.env.TELEGRAM_API_HASH) &&
    Boolean(process.env.TELEGRAM_SESSION);
  if (!configured) return [] satisfies TgMessage[]; // track off — no errors
  // Phase 6 wires the real listener here; until then, nothing arrives on this path.
  return [] satisfies TgMessage[];
}

// node:detect-hook — Detect the hook from the first words (single entry point) [router]
async function detectHook(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  // Single entry point: merge both reception tracks (bot chat + any-chat userbot).
  const messages = [
    ...((artifacts["fetch-telegram-updates"] as TgMessage[]) ?? []),
    ...((artifacts["userbot-fetch-messages"] as TgMessage[]) ?? []),
  ];
  if (!messages.length) return [] satisfies Classified2[];

  // Active hooks from the GLOBAL project_hooks table (step 187).
  const hooks = (await db
    .prepare("SELECT phrase, normalized_phrase, action, project FROM project_hooks")
    .all()) as Array<{ phrase: string; normalized_phrase: string; action: string; project: string }>;

  const out: Classified2[] = [];
  for (const msg of messages) {
    const firstWords = msg.text.split(/\s+/).slice(0, 20).join(" ");
    const normFirst = normalizePhrase(firstWords);

    // Fast path: a normalized hook phrase is a prefix of the normalized message start.
    let matched = hooks.find((h) => normFirst.startsWith(h.normalized_phrase) && h.normalized_phrase.length > 0);

    // AI path: no cheap prefix hit — ask the cheap model whether the opening contains a hook.
    if (!matched && hooks.length) {
      const list = hooks.map((h, i) => `${i}: "${h.phrase}" (${h.action})`).join("\n");
      const ans = await cheapModel(
        "You detect whether a message opening starts with one of the registered trigger phrases (hooks). " +
          "Reply with ONLY the index number of the matching hook, or -1 if none match. No other text.",
        `Hooks:\n${list}\n\nMessage opening: "${firstWords}"`,
        8,
      );
      const idx = Number((ans.match(/-?\d+/) ?? ["-1"])[0]);
      if (Number.isInteger(idx) && idx >= 0 && idx < hooks.length) matched = hooks[idx];
    }

    if (!matched) {
      out.push({ intent: "ignore", projectSlug: null, payload: "", hookPhrase: "", chatId: msg.chatId, messageId: msg.messageId, date: msg.date });
      continue;
    }

    // payload = text after the hook phrase (strip leading punctuation/spaces). Locate the
    // phrase case-insensitively in the raw text; fall back to trimming the first N words.
    const rawLower = msg.text.toLowerCase();
    const phraseLower = matched.phrase.toLowerCase();
    let payload = "";
    const at = rawLower.indexOf(phraseLower);
    if (at >= 0) payload = msg.text.slice(at + matched.phrase.length);
    else payload = msg.text.split(/\s+/).slice(matched.normalized_phrase.split(" ").length).join(" ");
    payload = payload.replace(/^[\s:,.!?—–-]+/, "").trim();

    const intent = (["save", "remind", "recall"].includes(matched.action) ? matched.action : "ignore") as Intent;
    if (intent === "ignore" || !payload) {
      out.push({ intent: "ignore", projectSlug: matched.project, payload: "", hookPhrase: matched.phrase, chatId: msg.chatId, messageId: msg.messageId, date: msg.date });
      continue;
    }
    out.push({ intent, projectSlug: matched.project, payload, hookPhrase: matched.phrase, chatId: msg.chatId, messageId: msg.messageId, date: msg.date });
  }
  return out;
}

// node:summarize-message — Detailed message summary (cheap model) [step]
async function summarizeMessage(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  const classified = (artifacts["detect-hook"] as Classified2[]) ?? [];
  const out: WithSummary[] = [];
  for (const c of classified) {
    if (c.intent !== "save" && c.intent !== "remind") continue;
    let summary = await cheapModel(
      "Summarize the user's note concisely but completely, preserving key facts, names and dates. " +
        "Reply with only the summary, one short paragraph.",
      c.payload.slice(0, 4000),
      200,
    );
    if (!summary) summary = c.payload.slice(0, 280); // graceful degrade
    out.push({ ...c, summary });
  }
  return out;
}

// node:search-memory-recall — Find an answer in the notes (LightRAG query) [step]
async function searchMemoryRecall(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  const classified = (artifacts["detect-hook"] as Classified2[]) ?? [];
  const out: RecallAnswer[] = [];
  for (const c of classified) {
    if (c.intent !== "recall") continue;
    try {
      const r = await fetch(`${RAG_URL}/query`, {
        method: "POST",
        headers: { "Content-Type": "application/json", "X-API-Key": RAG_KEY, "X-Agent-Identity": PROJECT_SLUG },
        body: JSON.stringify({ query: c.payload, mode: "hybrid" }),
        signal: AbortSignal.timeout(60_000),
      });
      if (!r.ok) {
        out.push({ chatId: c.chatId, query: c.payload, hookPhrase: c.hookPhrase, answer: "Memory is temporarily unavailable, please try again later.", error: `HTTP ${r.status}` });
        continue;
      }
      const data = (await r.json()) as { response?: string };
      const answer = (data.response ?? "").trim();
      out.push({
        chatId: c.chatId,
        query: c.payload,
        hookPhrase: c.hookPhrase,
        answer: answer || `Nothing found in your notes for: ${c.payload}`,
      });
    } catch (e) {
      out.push({ chatId: c.chatId, query: c.payload, hookPhrase: c.hookPhrase, answer: "Memory is temporarily unavailable, please try again later.", error: e instanceof Error ? e.message : String(e) });
    }
  }
  return out;
}

// node:persist-note-to-db — Write the note/reminder to the project DB [step]
// Writes one Record per save / remind / recall (188-R). Each row carries hook_phrase (the
// matched phrase) and condition (the declared-guard outcome) — the ontology trace: what the
// user said → what matched → what ran.
async function persistNoteToDb(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  const withSummary = (artifacts["summarize-message"] as WithSummary[]) ?? [];
  const recalls = (artifacts["search-memory-recall"] as RecallAnswer[]) ?? [];
  const out: Persisted[] = [];

  for (const item of withSummary) {
    let reminderDue: number | null = null;
    let needsWhen = false;
    let condition: string | null = null;

    if (item.intent === "remind") {
      // Ask the cheap model for an ISO datetime in the payload; "none" → needs a "when?".
      const nowIso = new Date().toISOString();
      const parsed = await cheapModel(
        `Current time is ${nowIso}. Extract the reminder date-time from the user's text and reply with ONLY an ISO-8601 datetime (e.g. 2026-07-06T19:05:00). If no specific time is given, reply with only the word: none.`,
        item.payload.slice(0, 500),
        40,
      );
      const iso = (parsed.match(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2})?/) ?? [])[0];
      if (iso) {
        const t = Math.floor(new Date(iso).getTime() / 1000);
        if (Number.isFinite(t) && t > 0) { reminderDue = t; condition = "date-parsed"; }
        else { needsWhen = true; condition = "needs-date"; }
      } else {
        needsWhen = true;
        condition = "needs-date";
      }
    }

    if (needsWhen) {
      // No date yet — do not persist a reminder row; reply will ask "when?".
      out.push({ dbId: null, intent: item.intent, reminderDue: null, needsWhen: true, chatId: item.chatId, summary: item.summary, payload: item.payload });
      continue;
    }

    const res = await db
      .prepare(
        "INSERT INTO telegram_notes (project_slug, hook_action, hook_phrase, condition, chat_id, msg_date, reminder_due, full_text, summary) " +
          "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
      )
      .run(PROJECT_SLUG, item.intent, item.hookPhrase, condition, item.chatId, item.date, reminderDue, item.payload, item.summary);
    const dbId = Number((res as { lastInsertRowid?: number | bigint }).lastInsertRowid ?? 0) || null;
    out.push({ dbId, intent: item.intent, reminderDue, needsWhen: false, chatId: item.chatId, summary: item.summary, payload: item.payload });
  }

  // Recall is ALSO a Record (188-R): every memory search becomes a "request" row so it shows
  // in the universal table. full_text = the question; summary = question + a digest of the answer.
  for (const rc of recalls) {
    const digest = rc.answer.replace(/\s+/g, " ").slice(0, 200);
    const summary = `Q: ${rc.query} — A: ${digest}`;
    await db
      .prepare(
        "INSERT INTO telegram_notes (project_slug, hook_action, hook_phrase, condition, chat_id, reminder_due, full_text, summary) " +
          "VALUES (?, 'recall', ?, NULL, ?, NULL, ?, ?)",
      )
      .run(PROJECT_SLUG, rc.hookPhrase, rc.chatId, rc.query, summary);
  }

  return out;
}

// node:ingest-note-to-memory — Write the note to vector memory (LightRAG) [step]
async function ingestNoteToMemory(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  const persisted = (artifacts["persist-note-to-db"] as Persisted[]) ?? [];
  const out: Ingested[] = [];
  for (const p of persisted) {
    if (p.dbId == null) continue; // needs-when rows are not yet stored
    const when = new Date().toISOString().slice(0, 16).replace("T", " ");
    const doc = `Project: ${PROJECT_SLUG} | Hook: ${p.intent} | Date: ${when} | Record #${p.dbId} | ${p.payload}`;
    try {
      const r = await fetch(`${RAG_URL}/documents/text`, {
        method: "POST",
        headers: { "Content-Type": "application/json", "X-API-Key": RAG_KEY, "X-Agent-Identity": PROJECT_SLUG },
        body: JSON.stringify({ text: doc, description: `telegram-notes #${p.dbId}` }),
        signal: AbortSignal.timeout(60_000),
      });
      // Capture the LightRAG track id so the record can be deleted from BOTH stores later
      // (188-R V2.5 Record delete contract): on delete we resolve this track id to the vector
      // doc id(s) and remove them. Best-effort — a missing id only means no vector delete.
      if (r.ok) {
        try {
          const data = (await r.json()) as { track_id?: string };
          if (data?.track_id && p.dbId != null) {
            await db
              .prepare("UPDATE telegram_notes SET memory_track_id = ? WHERE id = ?")
              .run(data.track_id, p.dbId);
          }
        } catch {
          /* response not JSON — the ingest still succeeded, we just lack the track id */
        }
      }
      out.push({ dbId: p.dbId, chatId: p.chatId, summary: p.summary, ingestOk: r.ok, error: r.ok ? undefined : `HTTP ${r.status}` });
    } catch (e) {
      out.push({ dbId: p.dbId, chatId: p.chatId, summary: p.summary, ingestOk: false, error: e instanceof Error ? e.message : String(e) });
    }
  }
  return out;
}

// node:reply-in-telegram — Reply to the user in Telegram [step]
async function replyInTelegram(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  const persisted = (artifacts["persist-note-to-db"] as Persisted[]) ?? [];
  const ingested = (artifacts["ingest-note-to-memory"] as Ingested[]) ?? [];
  const recalls = (artifacts["search-memory-recall"] as RecallAnswer[]) ?? [];
  const ingestById = new Map(ingested.map((i) => [i.dbId, i]));

  const errors: string[] = [];
  let saved = 0;
  let reminded = 0;
  let answered = 0;

  for (const p of persisted) {
    try {
      if (p.needsWhen) {
        await tgSend(p.chatId, "When should I remind you? Reply with a date and time (for example: today at 19:05).");
        continue;
      }
      if (p.intent === "save") {
        const ing = ingestById.get(p.dbId);
        if (ing && ing.ingestOk) {
          await tgSend(p.chatId, `Saved: ${p.summary}`);
          saved++;
        } else {
          await tgSend(p.chatId, `Saved, but memory is unavailable — I'll index it later. (${ing?.error ?? "ingest error"})`);
          saved++;
        }
      } else if (p.intent === "remind" && p.reminderDue) {
        const when = new Date(p.reminderDue * 1000);
        const hhmm = `${String(when.getHours()).padStart(2, "0")}:${String(when.getMinutes()).padStart(2, "0")}`;
        await tgSend(p.chatId, `I'll remind you at ${hhmm}: ${p.summary}`);
        reminded++;
      }
    } catch (e) {
      errors.push(`reply ${p.dbId ?? "?"}: ${e instanceof Error ? e.message : String(e)}`);
    }
  }

  for (const rc of recalls) {
    try {
      await tgSend(rc.chatId, rc.answer);
      answered++;
    } catch (e) {
      errors.push(`recall reply: ${e instanceof Error ? e.message : String(e)}`);
    }
  }

  return { processed: persisted.length + recalls.length, saved, reminded, answered, errors };
}
