import { journalRunStart, journalRunFinish } from "./journal";
import { db } from "@/lib/db";

// fractera:workflow os-629d27a2ddcfd5e5 — GENERATED by orchestrate-project-by-steps from the
// decomposition graph (step 184, contract R6; automation ontology 188-R), BODIES implemented by
// Claude Code (step 188, variant B: self-sufficient poller — NO native Hermes gateway, zero Hermes
// runtime load). This workflow is the EXECUTABLE mirror of the diagram in the project page's
// _data/flow.ts — the two are ISOMORPHIC: one "use step" function per non-trigger diagram
// node, in topological order, each under its `// node:<id>` marker. A new Action = extend the
// GRAPH and re-run the engine — a shadow step outside the diagram is forbidden.
//
// Trigger node(s) of the diagram — not steps; the run route (../run/route.ts) and the
// project's cron queue fire this workflow (automation ontology 188-R):
//   • "reception-trigger" — reception wake-up (interim cron; target: always-on long-poll listener)
//   • "reminder-cron-trigger" — the schedule that delivers due reminders
//   • "userbot-reception-trigger" — any-chat MTProto reception (advanced track, Phase 6)

// ── Shared config (self-sufficient: read from the slot's own env, never Hermes) ──
const TG_API = "https://api.telegram.org";
const OPENAI_URL = "https://api.openai.com/v1/chat/completions";
const CHEAP_MODEL = process.env.TELEGRAM_NOTES_MODEL ?? "gpt-4o-mini";
const RAG_URL = (process.env.LIGHTRAG_URL ?? "http://localhost:9621").replace(/\/+$/, "");
const RAG_KEY = process.env.LIGHTRAG_API_KEY ?? "";
const PROJECT_SLUG = "telegram-notes";

type TgMessage = { chatId: string; messageId: number; text: string; date: number; forcedAction?: Intent };
type Intent = "save" | "remind" | "recall" | "ignore";
type Classified = {
  intent: Intent;
  projectSlug: string | null;
  payload: string;
  chatId: string;
  messageId: number;
  date: number;
};
// hookPhrase = legacy trace field, kept for the DB column (hook_phrase); step 205 removed hooks, so
// classify-message leaves it "". Retained (backward-compatible) so the persisted schema is unchanged.
type Classified2 = Classified & { hookPhrase: string; unclear?: boolean };
type WithSummary = Classified2 & { summary: string };
type Persisted = {
  dbId: number | null;
  intent: Intent;
  reminderDue: number | null;
  needsWhen: boolean;
  chatId: string;
  summary: string;
  payload: string;
};
type Ingested = { dbId: number | null; chatId: string; ingestOk: boolean; summary: string; error?: string };
// recall answers carry the query + the db row id so the reply and the record line up (188-R).
type RecallAnswer = { chatId: string; answer: string; query: string; hookPhrase: string; error?: string };

// ── Small helpers (plain functions — no "use step") ──

function botToken(): string {
  const t = process.env.TELEGRAM_BOT_TOKEN ?? "";
  if (!t) throw new Error("TELEGRAM_BOT_TOKEN is not set in the slot env (rule 143)");
  return t;
}

async function tgSend(chatId: string, text: string): Promise<void> {
  // Telegram caps messages at 4096 chars — split on paragraph/sentence boundaries.
  const chunks: string[] = [];
  let rest = text;
  while (rest.length > 4096) {
    let cut = rest.lastIndexOf("\n", 4096);
    if (cut < 2000) cut = rest.lastIndexOf(". ", 4096);
    if (cut < 2000) cut = 4096;
    chunks.push(rest.slice(0, cut));
    rest = rest.slice(cut);
  }
  chunks.push(rest);
  for (const chunk of chunks) {
    await fetch(`${TG_API}/bot${botToken()}/sendMessage`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      // plain text on purpose — free-form notes must not break on Markdown specials.
      body: JSON.stringify({ chat_id: chatId, text: chunk }),
    }).catch(() => undefined);
  }
}

// One cheap-model chat completion. Returns the assistant text (trimmed) or "" on failure —
// callers degrade gracefully (the automation never dies because the model hiccuped).
async function cheapModel(system: string, user: string, maxTokens = 400): Promise<string> {
  const key = process.env.OPENAI_API_KEY ?? "";
  if (!key) return "";
  try {
    const r = await fetch(OPENAI_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` },
      body: JSON.stringify({
        model: CHEAP_MODEL,
        messages: [
          { role: "system", content: system },
          { role: "user", content: user },
        ],
        temperature: 0,
        max_tokens: maxTokens,
      }),
      signal: AbortSignal.timeout(30_000),
    });
    if (!r.ok) return "";
    const data = (await r.json()) as { choices?: Array<{ message?: { content?: string } }> };
    return (data.choices?.[0]?.message?.content ?? "").trim();
  } catch {
    return "";
  }
}

// ── Inline-button fallback helpers (step 205 §D): when classify-message is unsure, the bot offers
// action buttons; the user's tap comes back as a callback the listener forwards here. ──
async function tgAnswerCallback(callbackQueryId: string): Promise<void> {
  if (!callbackQueryId) return;
  try {
    await fetch(`${TG_API}/bot${botToken()}/answerCallbackQuery`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ callback_query_id: callbackQueryId }),
    });
  } catch { /* best-effort */ }
}

async function tgSendButtons(
  chatId: string,
  text: string,
  buttons: Array<{ text: string; data: string }>,
): Promise<void> {
  try {
    await fetch(`${TG_API}/bot${botToken()}/sendMessage`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        chat_id: chatId,
        text,
        reply_markup: { inline_keyboard: buttons.map((b) => [{ text: b.text, callback_data: b.data }]) },
      }),
    });
  } catch { /* best-effort */ }
}

// Pending store: the original message text held under a short id while the user picks an action from the
// buttons (callback_data is limited to 64 bytes, so we key the text, not carry it).
async function storePending(text: string, chatId: string): Promise<string> {
  const id = crypto.randomUUID().slice(0, 8);
  try {
    await db
      .prepare("INSERT OR REPLACE INTO telegram_notes_state (key, value) VALUES (?, ?)")
      .run(`pending:${id}`, JSON.stringify({ text, chatId }));
  } catch { /* state table optional */ }
  return id;
}
async function loadPending(id: string): Promise<{ text: string; chatId: string } | null> {
  try {
    const row = (await db
      .prepare("SELECT value FROM telegram_notes_state WHERE key = ?")
      .get(`pending:${id}`)) as { value?: string } | null;
    if (row?.value) return JSON.parse(row.value) as { text: string; chatId: string };
  } catch { /* missing/parse */ }
  return null;
}

export async function runProject(input?: string) {
  "use workflow";

  const journalId = await openRun(input);
  const artifacts: Record<string, unknown> = { input };
  try {
    artifacts["fetch-telegram-updates"] = await fetchTelegramUpdates(artifacts);
    artifacts["deliver-due-reminders"] = await deliverDueReminders(artifacts);
    artifacts["classify-message"] = await classifyMessage(artifacts);
    artifacts["summarize-message"] = await summarizeMessage(artifacts);
    artifacts["search-memory-recall"] = await searchMemoryRecall(artifacts);
    artifacts["persist-note-to-db"] = await persistNoteToDb(artifacts);
    artifacts["ingest-note-to-memory"] = await ingestNoteToMemory(artifacts);
    const outcome = (await replyInTelegram(artifacts)) as {
      processed: number;
      saved: number;
      reminded: number;
      answered: number;
      errors: string[];
    };
    artifacts["reply-in-telegram"] = outcome;
    const title =
      `processed ${outcome.processed} · saved ${outcome.saved} · reminded ${outcome.reminded} · answered ${outcome.answered}` +
      (outcome.errors.length ? ` · ${outcome.errors.length} error(s)` : "");
    await closeRun(journalId, { ok: true, resultTitle: title });
    return { journalId, status: "completed" };
  } catch (e) {
    await closeRun(journalId, {
      ok: false,
      error: e instanceof Error ? e.message : String(e),
    });
    throw e;
  }
}

// Journal steps — write the run into project_cron_runs, the same table the
// queue/results tables of the project page read.

async function openRun(input?: string) {
  "use step";

  const id = crypto.randomUUID();
  journalRunStart(id, input);
  return id;
}

async function closeRun(
  id: string,
  result: { ok: boolean; resultTitle?: string; resultUrl?: string; error?: string },
) {
  "use step";

  journalRunFinish(id, result);
}

// ── Diagram-mirror steps (one per non-trigger node, topological order) ──

// node:fetch-telegram-updates — Reception from the @fractera_auto listener [step]
// Step 201 (agent-channel-routing.md §3): reception is now delivered by the substrate
// fractera-automations listener, NOT self-polled. This automation MUST NOT call getUpdates
// itself — a second consumer of the bot re-creates the message-stealing collision (the whole
// reason the listener exists). Input arrives as the listener's JSON envelope; a plain string
// remains supported as the run-panel manual test (simulateMessage).
async function fetchTelegramUpdates(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  const allowedChat = process.env.TELEGRAM_ALLOWED_CHAT_ID ?? "";
  const raw = typeof artifacts.input === "string" ? (artifacts.input as string).trim() : "";

  // Empty input = a scheduled /run tick (reminder delivery) or a bare trigger — NO message to
  // process, and we never poll. deliver-due-reminders still runs on the tick.
  if (!raw) return [] satisfies TgMessage[];

  // Listener envelope: the fractera-automations service (step 205) forwards EVERY message from this
  // automation's own bot here — no hook matching; the bot identity already selected this automation.
  try {
    const env = JSON.parse(raw) as {
      source?: string; kind?: string; data?: unknown; callbackQueryId?: unknown;
      chatId?: unknown; messageId?: unknown; text?: unknown; date?: unknown;
    };
    // Callback from an inline button (step 205 §D): the user picked an action for an earlier "unclear"
    // message. Resolve the pending text + forced action, ack the tap, and feed it back into the pipeline.
    if (env && env.source === "telegram" && env.kind === "callback" && typeof env.data === "string") {
      const cbChat = String(env.chatId ?? "");
      if (allowedChat && cbChat && cbChat !== allowedChat) return [] satisfies TgMessage[];
      await tgAnswerCallback(String(env.callbackQueryId ?? ""));
      const sep = env.data.indexOf(":");
      const pid = sep >= 0 ? env.data.slice(0, sep) : "";
      const action = sep >= 0 ? env.data.slice(sep + 1) : "ignore";
      const pending = await loadPending(pid);
      if (!pending) return [] satisfies TgMessage[];
      const act = (["save", "remind", "recall", "ignore"].includes(action) ? action : "ignore") as Intent;
      if (act === "ignore") {
        await tgSend(pending.chatId, "Okay — ignored.");
        return [] satisfies TgMessage[];
      }
      return [
        { chatId: pending.chatId, messageId: 0, text: pending.text, date: Math.floor(Date.now() / 1000), forcedAction: act },
      ] satisfies TgMessage[];
    }
    if (env && env.source === "telegram" && typeof env.text === "string") {
      const chatId = String(env.chatId ?? "");
      if (allowedChat && chatId && chatId !== allowedChat) return [] satisfies TgMessage[];
      const finalChat = chatId || allowedChat || "0";
      // Remember the owner's chat so the "Test bot" button can send them a message (a bot cannot
      // initiate a chat — it needs a chat the owner has already talked to). Best-effort (step 205).
      try {
        db.prepare(
          "INSERT OR REPLACE INTO telegram_notes_state (key, value) VALUES ('last_chat_id', ?)",
        ).run(finalChat);
      } catch { /* state table optional */ }
      return [
        {
          chatId: finalChat,
          messageId: Number(env.messageId ?? 0),
          text: env.text,
          date: Number(env.date ?? Math.floor(Date.now() / 1000)),
        },
      ] satisfies TgMessage[];
    }
  } catch {
    // not JSON → fall through to the plain-string manual-test branch
  }

  // Run-panel manual test branch: a plain string is a single message from the allowed chat.
  return [
    { chatId: allowedChat || "0", messageId: 0, text: raw, date: Math.floor(Date.now() / 1000) },
  ] satisfies TgMessage[];
}

// node:deliver-due-reminders — Deliver due reminders (date push) [step]
async function deliverDueReminders(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";
  void artifacts;

  const now = Math.floor(Date.now() / 1000);
  const due = (await db
    .prepare(
      "SELECT id, chat_id, reminder_due, full_text, summary FROM telegram_notes " +
        "WHERE reminder_due IS NOT NULL AND reminder_due <= ? AND delivered = 0",
    )
    .all(now)) as Array<{ id: number; chat_id: string; reminder_due: number; full_text: string; summary: string }>;

  const errors: string[] = [];
  let delivered = 0;
  for (const row of due) {
    const when = new Date(row.reminder_due * 1000);
    const hhmm = `${String(when.getHours()).padStart(2, "0")}:${String(when.getMinutes()).padStart(2, "0")}`;
    const what = row.summary || row.full_text;
    try {
      await tgSend(row.chat_id, `Reminder: you asked to be reminded at ${hhmm} to ${what}`);
      await db.prepare("UPDATE telegram_notes SET delivered = 1 WHERE id = ?").run(row.id);
      delivered++;
    } catch (e) {
      errors.push(`reminder ${row.id}: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
  return { delivered, errors };
}

// node:classify-message — Classify the message into one of this automation's actions [router]
// Step 205 (§D, agent-channel-routing.md §3.1): this automation owns its Telegram bot, so there is
// NO cross-automation hook registry. Each message is classified into one of THIS automation's actions
// with the per-project cheap model; clear → that action, unclear → ignore for now (the inline-button
// fallback is step 205.10). payload = the whole message (there is no hook phrase to strip).
async function classifyMessage(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  const messages = ((artifacts["fetch-telegram-updates"] as TgMessage[]) ?? []);
  if (!messages.length) return [] satisfies Classified2[];

  const out: Classified2[] = [];
  for (const msg of messages) {
    // A button tap (callback) carries a forced action — skip the model, honor the user's choice.
    if (msg.forcedAction) {
      out.push({ intent: msg.forcedAction, projectSlug: PROJECT_SLUG, payload: msg.text, hookPhrase: "", chatId: msg.chatId, messageId: msg.messageId, date: msg.date });
      continue;
    }
    const text = msg.text.trim();
    let intent: Intent = "ignore";
    let unclear = false;
    if (text) {
      const ans = await cheapModel(
        "You route one message of a personal-notes assistant to a single action. Reply with ONLY one word: " +
          "save (the user states a fact/note to remember), remind (the user wants a time-based reminder), " +
          "recall (the user asks to find/retrieve something they saved), or unclear (none clearly applies). " +
          "No other text.",
        text.slice(0, 1000),
        4,
      );
      const word = (ans.toLowerCase().match(/save|remind|recall|unclear/) ?? ["unclear"])[0];
      if (word === "unclear") { intent = "ignore"; unclear = true; }
      else intent = word as Intent;
    }
    out.push({
      intent,
      projectSlug: PROJECT_SLUG,
      // unclear keeps the text so reply-in-telegram can offer buttons; a plain empty message stays "".
      payload: intent === "ignore" ? (unclear ? text : "") : text,
      hookPhrase: "",
      unclear,
      chatId: msg.chatId,
      messageId: msg.messageId,
      date: msg.date,
    });
  }
  return out;
}

// node:summarize-message — Detailed message summary (cheap model) [step]
async function summarizeMessage(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  const classified = (artifacts["classify-message"] as Classified2[]) ?? [];
  const out: WithSummary[] = [];
  for (const c of classified) {
    if (c.intent !== "save" && c.intent !== "remind") continue;
    let summary = await cheapModel(
      "Summarize the user's note concisely but completely, preserving key facts, names and dates. " +
        "Reply with only the summary, one short paragraph.",
      c.payload.slice(0, 4000),
      200,
    );
    if (!summary) summary = c.payload.slice(0, 280); // graceful degrade
    out.push({ ...c, summary });
  }
  return out;
}

// node:search-memory-recall — Find an answer in the notes (LightRAG query) [step]
async function searchMemoryRecall(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  const classified = (artifacts["classify-message"] as Classified2[]) ?? [];
  const out: RecallAnswer[] = [];
  for (const c of classified) {
    if (c.intent !== "recall") continue;
    try {
      const r = await fetch(`${RAG_URL}/query`, {
        method: "POST",
        headers: { "Content-Type": "application/json", "X-API-Key": RAG_KEY, "X-Agent-Identity": PROJECT_SLUG },
        body: JSON.stringify({ query: c.payload, mode: "hybrid" }),
        signal: AbortSignal.timeout(60_000),
      });
      if (!r.ok) {
        out.push({ chatId: c.chatId, query: c.payload, hookPhrase: c.hookPhrase, answer: "Memory is temporarily unavailable, please try again later.", error: `HTTP ${r.status}` });
        continue;
      }
      const data = (await r.json()) as { response?: string };
      const answer = (data.response ?? "").trim();
      out.push({
        chatId: c.chatId,
        query: c.payload,
        hookPhrase: c.hookPhrase,
        answer: answer || `Nothing found in your notes for: ${c.payload}`,
      });
    } catch (e) {
      out.push({ chatId: c.chatId, query: c.payload, hookPhrase: c.hookPhrase, answer: "Memory is temporarily unavailable, please try again later.", error: e instanceof Error ? e.message : String(e) });
    }
  }
  return out;
}

// node:persist-note-to-db — Write the note/reminder to the project DB [step]
// Writes one Record per save / remind / recall (188-R). Each row carries hook_phrase (the
// matched phrase) and condition (the declared-guard outcome) — the ontology trace: what the
// user said → what matched → what ran.
async function persistNoteToDb(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  const withSummary = (artifacts["summarize-message"] as WithSummary[]) ?? [];
  const recalls = (artifacts["search-memory-recall"] as RecallAnswer[]) ?? [];
  const out: Persisted[] = [];

  for (const item of withSummary) {
    let reminderDue: number | null = null;
    let needsWhen = false;
    let condition: string | null = null;

    if (item.intent === "remind") {
      // Ask the cheap model for an ISO datetime in the payload; "none" → needs a "when?".
      const nowIso = new Date().toISOString();
      const parsed = await cheapModel(
        `Current time is ${nowIso}. Extract the reminder date-time from the user's text and reply with ONLY an ISO-8601 datetime (e.g. 2026-07-06T19:05:00). If no specific time is given, reply with only the word: none.`,
        item.payload.slice(0, 500),
        40,
      );
      const iso = (parsed.match(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2})?/) ?? [])[0];
      if (iso) {
        const t = Math.floor(new Date(iso).getTime() / 1000);
        if (Number.isFinite(t) && t > 0) { reminderDue = t; condition = "date-parsed"; }
        else { needsWhen = true; condition = "needs-date"; }
      } else {
        needsWhen = true;
        condition = "needs-date";
      }
    }

    if (needsWhen) {
      // No date yet — do not persist a reminder row; reply will ask "when?".
      out.push({ dbId: null, intent: item.intent, reminderDue: null, needsWhen: true, chatId: item.chatId, summary: item.summary, payload: item.payload });
      continue;
    }

    const res = await db
      .prepare(
        "INSERT INTO telegram_notes (project_slug, hook_action, hook_phrase, condition, chat_id, msg_date, reminder_due, full_text, summary) " +
          "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
      )
      .run(PROJECT_SLUG, item.intent, item.hookPhrase, condition, item.chatId, item.date, reminderDue, item.payload, item.summary);
    const dbId = Number((res as { lastInsertRowid?: number | bigint }).lastInsertRowid ?? 0) || null;
    out.push({ dbId, intent: item.intent, reminderDue, needsWhen: false, chatId: item.chatId, summary: item.summary, payload: item.payload });
  }

  // Recall is ALSO a Record (188-R): every memory search becomes a "request" row so it shows
  // in the universal table. full_text = the question; summary = question + a digest of the answer.
  for (const rc of recalls) {
    const digest = rc.answer.replace(/\s+/g, " ").slice(0, 200);
    const summary = `Q: ${rc.query} — A: ${digest}`;
    await db
      .prepare(
        "INSERT INTO telegram_notes (project_slug, hook_action, hook_phrase, condition, chat_id, reminder_due, full_text, summary) " +
          "VALUES (?, 'recall', ?, NULL, ?, NULL, ?, ?)",
      )
      .run(PROJECT_SLUG, rc.hookPhrase, rc.chatId, rc.query, summary);
  }

  return out;
}

// node:ingest-note-to-memory — Write the note to vector memory (LightRAG) [step]
async function ingestNoteToMemory(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  const persisted = (artifacts["persist-note-to-db"] as Persisted[]) ?? [];
  const out: Ingested[] = [];
  for (const p of persisted) {
    if (p.dbId == null) continue; // needs-when rows are not yet stored
    const when = new Date().toISOString().slice(0, 16).replace("T", " ");
    const doc = `Project: ${PROJECT_SLUG} | Hook: ${p.intent} | Date: ${when} | Record #${p.dbId} | ${p.payload}`;
    try {
      const r = await fetch(`${RAG_URL}/documents/text`, {
        method: "POST",
        headers: { "Content-Type": "application/json", "X-API-Key": RAG_KEY, "X-Agent-Identity": PROJECT_SLUG },
        body: JSON.stringify({ text: doc, description: `telegram-notes #${p.dbId}` }),
        signal: AbortSignal.timeout(60_000),
      });
      // Capture the LightRAG track id so the record can be deleted from BOTH stores later
      // (188-R V2.5 Record delete contract): on delete we resolve this track id to the vector
      // doc id(s) and remove them. Best-effort — a missing id only means no vector delete.
      if (r.ok) {
        try {
          const data = (await r.json()) as { track_id?: string };
          if (data?.track_id && p.dbId != null) {
            await db
              .prepare("UPDATE telegram_notes SET memory_track_id = ? WHERE id = ?")
              .run(data.track_id, p.dbId);
          }
        } catch {
          /* response not JSON — the ingest still succeeded, we just lack the track id */
        }
      }
      out.push({ dbId: p.dbId, chatId: p.chatId, summary: p.summary, ingestOk: r.ok, error: r.ok ? undefined : `HTTP ${r.status}` });
    } catch (e) {
      out.push({ dbId: p.dbId, chatId: p.chatId, summary: p.summary, ingestOk: false, error: e instanceof Error ? e.message : String(e) });
    }
  }
  return out;
}

// node:reply-in-telegram — Reply to the user in Telegram [step]
async function replyInTelegram(artifacts: Record<string, unknown>): Promise<unknown> {
  "use step";

  const persisted = (artifacts["persist-note-to-db"] as Persisted[]) ?? [];
  const ingested = (artifacts["ingest-note-to-memory"] as Ingested[]) ?? [];
  const recalls = (artifacts["search-memory-recall"] as RecallAnswer[]) ?? [];
  const classified = (artifacts["classify-message"] as Classified2[]) ?? [];
  const ingestById = new Map(ingested.map((i) => [i.dbId, i]));

  const errors: string[] = [];
  let saved = 0;
  let reminded = 0;
  let answered = 0;

  for (const p of persisted) {
    try {
      if (p.needsWhen) {
        await tgSend(p.chatId, "When should I remind you? Reply with a date and time (for example: today at 19:05).");
        continue;
      }
      if (p.intent === "save") {
        const ing = ingestById.get(p.dbId);
        if (ing && ing.ingestOk) {
          await tgSend(p.chatId, `Saved: ${p.summary}`);
          saved++;
        } else {
          await tgSend(p.chatId, `Saved, but memory is unavailable — I'll index it later. (${ing?.error ?? "ingest error"})`);
          saved++;
        }
      } else if (p.intent === "remind" && p.reminderDue) {
        const when = new Date(p.reminderDue * 1000);
        const hhmm = `${String(when.getHours()).padStart(2, "0")}:${String(when.getMinutes()).padStart(2, "0")}`;
        await tgSend(p.chatId, `I'll remind you at ${hhmm}: ${p.summary}`);
        reminded++;
      }
    } catch (e) {
      errors.push(`reply ${p.dbId ?? "?"}: ${e instanceof Error ? e.message : String(e)}`);
    }
  }

  for (const rc of recalls) {
    try {
      await tgSend(rc.chatId, rc.answer);
      answered++;
    } catch (e) {
      errors.push(`recall reply: ${e instanceof Error ? e.message : String(e)}`);
    }
  }

  // Unclear messages (step 205 §D): offer action buttons instead of silently ignoring. The tap comes
  // back as a callback (handled in fetch-telegram-updates) carrying a forced action.
  let prompted = 0;
  for (const c of classified) {
    if (!c.unclear || !c.payload) continue;
    try {
      const pid = await storePending(c.payload, c.chatId);
      await tgSendButtons(c.chatId, "I'm not sure what to do with that — pick one:", [
        { text: "💾 Save it", data: `${pid}:save` },
        { text: "⏰ Remind me", data: `${pid}:remind` },
        { text: "🔎 Find it", data: `${pid}:recall` },
        { text: "✖ Sent by mistake", data: `${pid}:ignore` },
      ]);
      prompted++;
    } catch (e) {
      errors.push(`prompt: ${e instanceof Error ? e.message : String(e)}`);
    }
  }

  return { processed: persisted.length + recalls.length + prompted, saved, reminded, answered, errors };
}
