#!/usr/bin/env node
// parser-routes — derive the route manifest from the filesystem (no hand edits).
//
// Globs every app/**/_meta.ts (the typed RouteMeta each route ships) and emits
// lib/architecture/routes.generated.ts: a path -> RouteMeta map + a node list that
// carries the real route GROUP ((service) etc). This is the "later codegen can glob
// these" the hand-kept route-manifest.ts / routes.ts promise — so a newly created
// route (incl. a constructor-composed group) appears automatically with its records,
// with the real (group) structure, and never drifts from the code on disk.
//
// URL path rules (match the existing manifest convention):
//   • strip route groups (group)         -> (service)/dashboard => /dashboard
//   • strip the leading i18n [lang] seg  -> [lang]/news => /news ; [lang] => /
//   • keep other dynamic segments [id]   -> api/projects/[id] => /api/projects/[id]
// kind is read from the sibling file: page.* => page, route.* => api.
//
// Run via gen:routes (wired into predev/prebuild). Deterministic; overwrites the
// generated file each run. Pure Node, no deps.

import { readdir, writeFile, stat } from "node:fs/promises"
import { join, resolve, relative } from "node:path"

const ROOT = resolve(process.cwd())
const APP = join(ROOT, "app")
const SKIP = new Set(["node_modules", ".next", "_components", "_lib", "_data"])
const PAGE_FILES = ["page.tsx", "page.ts", "page.jsx", "page.js"]
const ROUTE_FILES = ["route.ts", "route.js"]
const LANG_SEG = "[lang]"

const isGroup = s => s.startsWith("(") && s.endsWith(")")

// folderRel like "(service)/dashboard" or "[lang]/news" -> URL path
function urlPath(folderRel) {
  const segs = folderRel.split("/").filter(Boolean)
  const out = []
  for (let i = 0; i < segs.length; i++) {
    const s = segs[i]
    if (isGroup(s)) continue                 // route group: transparent to the URL
    if (i === 0 && s === LANG_SEG) continue  // leading i18n locale prefix -> "/"
    out.push(s)
  }
  const p = out.join("/")
  return p ? "/" + p : "/"
}

function routeGroupOf(folderRel) {
  const g = folderRel.split("/").filter(isGroup).map(s => s).pop()
  return g ?? null
}

async function walk(dir, out = []) {
  let entries
  try { entries = await readdir(dir, { withFileTypes: true }) } catch { return out }
  const names = new Set(entries.map(e => e.name))
  if (names.has("_meta.ts")) {
    const folderRel = relative(APP, dir).split("\\").join("/")
    const kind = PAGE_FILES.some(f => names.has(f)) ? "page"
      : ROUTE_FILES.some(f => names.has(f)) ? "api"
      : null // declared-only (_meta but no built file) — skip; fs-scan handles declared
    if (kind) {
      out.push({
        folderRel,
        importPath: `@/app/${folderRel}/_meta`,
        path: urlPath(folderRel),
        kind,
        group: routeGroupOf(folderRel),
      })
    }
  }
  for (const e of entries) {
    if (!e.isDirectory() || SKIP.has(e.name) || e.name.startsWith(".")) continue
    await walk(join(dir, e.name), out)
  }
  return out
}

function emit(routes) {
  // stable order: pages first, then api, each alphabetical by path
  routes.sort((a, b) => (a.kind === b.kind ? a.path.localeCompare(b.path) : a.kind === "page" ? -1 : 1))
  const imports = routes.map((r, i) => `import m${i} from "${r.importPath}"`).join("\n")
  const rows = routes.map((r, i) =>
    `  { path: ${JSON.stringify(r.path)}, kind: ${JSON.stringify(r.kind)}, group: ${JSON.stringify(r.group)}, meta: m${i} },`
  ).join("\n")
  return `// AUTO-GENERATED by lib/architecture/parser-routes.mjs — DO NOT EDIT.
// Regenerated on predev/prebuild (gen:routes). Derives the route manifest from the
// real app/**/_meta.ts on disk, so /architecture never drifts from the code.
import type { RouteMeta } from "./route-meta"
${imports}

export type GeneratedRoute = { path: string; kind: "page" | "api"; group: string | null; meta: RouteMeta }

export const GENERATED_ROUTES: GeneratedRoute[] = [
${rows}
]

export const GENERATED_ROUTE_META: Record<string, RouteMeta> =
  Object.fromEntries(GENERATED_ROUTES.map(r => [r.path, r.meta]))
`
}

async function main() {
  if (!(await stat(APP).catch(() => null))) { console.error("parser-routes: no app/ dir"); process.exit(1) }
  const routes = await walk(APP)
  const outFile = join(ROOT, "lib", "architecture", "routes.generated.ts")
  await writeFile(outFile, emit(routes), "utf8")
  console.log(`parser-routes: ${routes.length} routes -> lib/architecture/routes.generated.ts`)
  for (const r of routes) console.log(`  ${r.kind.padEnd(4)} ${r.path}${r.group ? `   [${r.group}]` : ""}`)
}

main().catch(e => { console.error("parser-routes:", e.message); process.exit(1) })
