// AUTO-GENERATED by lib/architecture/parser-routes.mjs — DO NOT EDIT.
// Regenerated on predev/prebuild (gen:routes). Derives the route manifest from the
// real app/**/_meta.ts on disk, so /architecture never drifts from the code.
import type { RouteMeta } from "./route-meta"
import m0 from "@/app/[lang]/_meta"
import m1 from "@/app/(service)/ai-core/_meta"
import m2 from "@/app/(service)/ai-draft-settings/_meta"
import m3 from "@/app/(service)/architecture/_meta"
import m4 from "@/app/(service)/dashboard/_meta"
import m5 from "@/app/(service)/debug/_meta"
import m6 from "@/app/(service)/development-steps/_meta"
import m7 from "@/app/(service)/documents/_meta"
import m8 from "@/app/(service)/glossary/_meta"
import m9 from "@/app/(service)/patterns/_meta"
import m10 from "@/app/(service)/project/my-telegram-reminder/_meta"
import m11 from "@/app/api/glossary/_meta"
import m12 from "@/app/api/health/_meta"
import m13 from "@/app/api/me/_meta"
import m14 from "@/app/api/media/[id]/file/_meta"
import m15 from "@/app/api/media/icons/[setId]/file/[name]/_meta"
import m16 from "@/app/api/media/upload/_meta"
import m17 from "@/app/api/project/default/architecture/requested/_meta"
import m18 from "@/app/api/project/default/architecture/requested/[id]/_meta"
import m19 from "@/app/api/project/default/architecture/signature/_meta"
import m20 from "@/app/api/project/default/architecture/tasks/_meta"
import m21 from "@/app/api/project/default/architecture/tasks/[id]/_meta"
import m22 from "@/app/api/project/default/products/_meta"
import m23 from "@/app/api/project/default/products/[id]/_meta"
import m24 from "@/app/api/project/default/routing/_meta"
import m25 from "@/app/api/project/default/source/_meta"
import m26 from "@/app/api/projects/_meta"
import m27 from "@/app/api/projects/[id]/_meta"

export type GeneratedRoute = { path: string; kind: "page" | "api"; group: string | null; meta: RouteMeta }

export const GENERATED_ROUTES: GeneratedRoute[] = [
  { path: "/", kind: "page", group: null, meta: m0 },
  { path: "/ai-core", kind: "page", group: "(service)", meta: m1 },
  { path: "/ai-draft-settings", kind: "page", group: "(service)", meta: m2 },
  { path: "/architecture", kind: "page", group: "(service)", meta: m3 },
  { path: "/dashboard", kind: "page", group: "(service)", meta: m4 },
  { path: "/debug", kind: "page", group: "(service)", meta: m5 },
  { path: "/development-steps", kind: "page", group: "(service)", meta: m6 },
  { path: "/documents", kind: "page", group: "(service)", meta: m7 },
  { path: "/glossary", kind: "page", group: "(service)", meta: m8 },
  { path: "/patterns", kind: "page", group: "(service)", meta: m9 },
  { path: "/project/my-telegram-reminder", kind: "page", group: "(service)", meta: m10 },
  { path: "/api/glossary", kind: "api", group: null, meta: m11 },
  { path: "/api/health", kind: "api", group: null, meta: m12 },
  { path: "/api/me", kind: "api", group: null, meta: m13 },
  { path: "/api/media/[id]/file", kind: "api", group: null, meta: m14 },
  { path: "/api/media/icons/[setId]/file/[name]", kind: "api", group: null, meta: m15 },
  { path: "/api/media/upload", kind: "api", group: null, meta: m16 },
  { path: "/api/project/default/architecture/requested", kind: "api", group: null, meta: m17 },
  { path: "/api/project/default/architecture/requested/[id]", kind: "api", group: null, meta: m18 },
  { path: "/api/project/default/architecture/signature", kind: "api", group: null, meta: m19 },
  { path: "/api/project/default/architecture/tasks", kind: "api", group: null, meta: m20 },
  { path: "/api/project/default/architecture/tasks/[id]", kind: "api", group: null, meta: m21 },
  { path: "/api/project/default/products", kind: "api", group: null, meta: m22 },
  { path: "/api/project/default/products/[id]", kind: "api", group: null, meta: m23 },
  { path: "/api/project/default/routing", kind: "api", group: null, meta: m24 },
  { path: "/api/project/default/source", kind: "api", group: null, meta: m25 },
  { path: "/api/projects", kind: "api", group: null, meta: m26 },
  { path: "/api/projects/[id]", kind: "api", group: null, meta: m27 },
]

export const GENERATED_ROUTE_META: Record<string, RouteMeta> =
  Object.fromEntries(GENERATED_ROUTES.map(r => [r.path, r.meta]))
