// fractera:actions os-629d27a2ddcfd5e5 — GENERATED by orchestrate-project-by-steps from the
// decomposition graph (automation ontology, step 188-R). An Action is a named outcome
// of this automation — a branch of steps triggered by its hook phrases. This registry
// is DERIVED (a re-run rewrites it): to add or change an action, extend the graph and
// re-run the engine. Canon: CRUD-DOCS/workspace-standards/automation-ontology.md.
export type ProjectActionHook = { phrase: string; lang: string };
export type ProjectAction = {
  id: string;
  title: string;
  description: string;
  color: string; // palette token — the UI maps it to theme-aware classes
  hooks: ProjectActionHook[];
  condition: string | null; // declared guard — implemented in the workflow step (R6)
  channel: string; // where this action's output is delivered
};

export const PROJECT_ACTIONS: ProjectAction[] = [
  {
    "id": "save",
    "title": "Save a note",
    "description": "Turns a message into a saved note: an AI summary plus the full text go to the project database and to vector memory, and the bot confirms.",
    "color": "blue",
    "hooks": [
      {
        "phrase": "кстати говоря, фрактера, запомни это",
        "lang": "ru"
      }
    ],
    "condition": null,
    "channel": "telegram-bot-chat"
  },
  {
    "id": "remind",
    "title": "Date reminder",
    "description": "Schedules an active push: at the requested date/time the bot sends the reminder text back to the chat.",
    "color": "amber",
    "hooks": [
      {
        "phrase": "кстати говоря, фрактера, напомни мне",
        "lang": "ru"
      }
    ],
    "condition": "a date/time is parsed from the message; otherwise the record is marked needs_when and the bot asks when to remind",
    "channel": "telegram-bot-chat"
  },
  {
    "id": "recall",
    "title": "Memory search",
    "description": "Answers a question from the saved notes: a semantic (vector) search over memory, replied in the chat and recorded as a request.",
    "color": "green",
    "hooks": [
      {
        "phrase": "кстати, фрактера, что я сохранял про",
        "lang": "ru"
      }
    ],
    "condition": null,
    "channel": "telegram-bot-chat"
  }
];

// Lookup helper — unknown ids resolve to a neutral placeholder (never undefined).
export function projectAction(id: string): ProjectAction {
  return (
    PROJECT_ACTIONS.find((a) => a.id === id) ?? {
      id, title: id, description: "", color: "neutral", hooks: [], condition: null, channel: "",
    }
  );
}