// fractera:columns os-decdaff68d1d7300 — GENERATED by orchestrate-project-by-steps from the graph's
// record.fields[] (automation ontology entity 12 Record, step 188-R). The universal RecordsTable
// renders whatever this declares through a CLOSED set of typed renderers; a re-run rewrites this
// file — to add or change a column, extend the GRAPH and re-run, never edit a component.
// Canon: CRUD-DOCS/workspace-standards/automation-ontology.md.

export type ColumnType = "badge" | "text" | "longtext" | "date" | "link" | "actions";
export type ColumnOptions = {
  colorFrom?: string;
  emphasizeIfFuture?: boolean;
  expand?: boolean;
  action?: "detail" | "delete";
};
export type ProjectColumn = {
  id: string;
  header: string;
  type: ColumnType;
  source: string;
  defaultVisible: boolean;
  attr?: string;
  options?: ColumnOptions;
};

// The DB table rows come from. Empty string = the generic completed-runs results.
export const RECORD_TABLE = "telegram_notes";

export const PROJECT_COLUMNS: ProjectColumn[] = [
  {
    "id": "action",
    "header": "Action",
    "type": "badge",
    "source": "hook_action",
    "defaultVisible": true,
    "attr": "action"
  },
  {
    "id": "hook",
    "header": "Hook",
    "type": "text",
    "source": "hook_phrase",
    "defaultVisible": true,
    "attr": "hook"
  },
  {
    "id": "summary",
    "header": "Summary",
    "type": "longtext",
    "source": "summary",
    "defaultVisible": true,
    "options": {
      "expand": true
    }
  },
  {
    "id": "condition",
    "header": "Condition",
    "type": "text",
    "source": "condition",
    "defaultVisible": false,
    "attr": "condition"
  },
  {
    "id": "reminder",
    "header": "Reminder",
    "type": "date",
    "source": "reminder_due",
    "defaultVisible": true,
    "options": {
      "emphasizeIfFuture": true
    }
  },
  {
    "id": "created",
    "header": "Created",
    "type": "date",
    "source": "created_at",
    "defaultVisible": true
  },
  {
    "id": "detail",
    "header": "detail",
    "type": "actions",
    "source": "id",
    "defaultVisible": true,
    "options": {
      "action": "detail"
    }
  },
  {
    "id": "delete",
    "header": "delete",
    "type": "actions",
    "source": "id",
    "defaultVisible": true,
    "options": {
      "action": "delete"
    }
  }
];

export function defaultVisibleColumnIds(): string[] {
  return PROJECT_COLUMNS.filter((c) => c.defaultVisible).map((c) => c.id);
}
export function projectColumn(id: string): ProjectColumn | undefined {
  return PROJECT_COLUMNS.find((c) => c.id === id);
}