import type { Edge, Node } from "@xyflow/react";

// fractera:flow os-bed7109d7be27ad4 — GENERATED by orchestrate-project-by-steps from the
// decomposition graph (step 184, contract R6). This diagram is the project's
// EXECUTION SCHEMA: what is not on it does not exist in the project. The file is
// DERIVED — a re-run rewrites it deterministically, so NEVER hand-edit it: to
// change the diagram, extend the graph and re-run the engine. Each node's `info`
// is the payload of the on-canvas info panel (R8).
export type FlowNodeInfo = {
  summary: string;
  processes: string[];
  kind: "trigger" | "action" | "transform";
  task?: string;
  tools: string[];
  envKeys: string[];
  io?: { in: unknown; out: unknown };
};

export type FlowNodeData = {
  label: string;
  info: FlowNodeInfo;
};

export type FlowNode = Node<FlowNodeData, "process">;

export const FLOW_NODES: FlowNode[] = [
  {
    "id": "telegram-cron-trigger",
    "type": "process",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "label": "Cron trigger: run the pipeline once a minute",
      "info": {
        "summary": "The entry point. Instead of a Telegram webhook (which needs HTTPS, is unavailable in IP mode, and would tie the project to the native Hermes gateway) it uses polling: a co-located cron.json schedules the run route every minute through fractera-cron (the substrate scheduler from step 179); the same route is available manually from the project page's run panel.",
        "processes": [
          "cron.json with the schedule * * * * * next to the project page",
          "run route: empty body from cron and {simulateMessage?} from the run panel",
          "the route returns runId, all logic lives in the workflow steps"
        ],
        "kind": "trigger",
        "task": "Set up the pipeline trigger. (1) Create a co-located cron.json in app/(projects)/projects/personal/telegram-notes/ with the schedule \"* * * * *\" (every minute), targeting POST /api/projects/personal/telegram-notes/run with an empty body — fractera-cron picks up a co-located cron.json automatically. (2) The run route (route.ts next to _workflow/definition.ts) accepts an empty body from cron and an optional manual input from the run panel ({ simulateMessage?: string } — for testing without Telegram: the string is processed as if it arrived from a chat). (3) The route starts a durable runProject run (WDK, world-local, step 183) and returns runId; no business logic in the route.",
        "tools": [
          "fractera-cron (co-located cron.json)",
          "run route POST /api/projects/personal/telegram-notes/run",
          "Workflow DevKit (world-local)"
        ],
        "envKeys": [],
        "io": {
          "in": "cron tick once a minute OR a manual run from the run panel (optional simulateMessage)",
          "out": "a started durable runProject run (runId)"
        }
      }
    }
  },
  {
    "id": "fetch-telegram-updates",
    "type": "process",
    "position": {
      "x": 260,
      "y": 0
    },
    "data": {
      "label": "Fetch new messages from Telegram (getUpdates)",
      "info": {
        "summary": "Polls the Telegram Bot API with getUpdates using a persistent last_update_id cursor, returning only the owner's new messages (the private chat with @fractera_bot).",
        "processes": [
          "telegram_notes_state table in SCHEMA (key/value, last_update_id cursor)",
          "getUpdates with offset and a TELEGRAM_ALLOWED_CHAT_ID filter",
          "cursor advances before processing (no repeats on failure)",
          "simulateMessage branch for testing without Telegram"
        ],
        "kind": "action",
        "task": "Implement the update-fetching step body. (1) Declare in SCHEMA (app/lib/db/index.ts — new tables ONLY in SCHEMA) the table telegram_notes_state (key TEXT PRIMARY KEY, value TEXT) for the last_update_id cursor. (2) GET https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getUpdates?offset=<last_update_id+1>&timeout=0 — a short request without long-poll (the step lives inside the one-minute tick). (3) Filter: only messages with text; if TELEGRAM_ALLOWED_CHAT_ID is set, drop other chats. (4) Advance the cursor to the maximum update_id IMMEDIATELY after reading (protects against reprocessing if a later step fails). (5) Return an array of {chatId, messageId, text, date}. (6) If a simulateMessage arrived from the run panel, return it as the single message with chatId = TELEGRAM_ALLOWED_CHAT_ID and do not poll Telegram. NEVER hardcode the token — env only (already in the slot .env.local, rule 143).",
        "tools": [
          "Telegram Bot API getUpdates",
          "SQLite via @/lib/db (SCHEMA)",
          "fetch"
        ],
        "envKeys": [
          "TELEGRAM_BOT_TOKEN",
          "TELEGRAM_ALLOWED_CHAT_ID"
        ],
        "io": {
          "in": "cron tick (empty) or simulateMessage from the run panel",
          "out": "array of new messages {chatId, messageId, text, date}; last_update_id cursor advanced"
        }
      }
    }
  },
  {
    "id": "deliver-due-reminders",
    "type": "process",
    "position": {
      "x": 260,
      "y": 100
    },
    "data": {
      "label": "Deliver due reminders (date push)",
      "info": {
        "summary": "The only active reminder action (type 1): on every cron tick it checks the DB for due reminder_due rows and sends the reminder text to the user in Telegram.",
        "processes": [
          "SELECT due reminder_due rows (not delivered)",
          "sendMessage with the verbatim reminder text",
          "mark delivered; delivered column in SCHEMA"
        ],
        "kind": "action",
        "task": "Implement reminder delivery. (1) SELECT from telegram_notes where reminder_due <= now AND not marked delivered. (2) For each: POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage to chat_id with the text \"Reminder: you asked to be reminded that at <HH:mm> you need to <payload/summary>\" (verbatim what the user set — the correct behavior from the owner's vision). (3) Mark the row delivered=1 (add the column to the SCHEMA table). (4) Runs as a parallel branch from the trigger — independent of new messages arriving. Log send failures, do not retry within the tick (the next tick will retry).",
        "tools": [
          "Telegram Bot API sendMessage",
          "SQLite via @/lib/db",
          "fetch"
        ],
        "envKeys": [
          "TELEGRAM_BOT_TOKEN"
        ],
        "io": {
          "in": "cron tick (checks due on every run)",
          "out": "{delivered: n, errors[]} — the reminders sent"
        }
      }
    }
  },
  {
    "id": "detect-hook",
    "type": "process",
    "position": {
      "x": 520,
      "y": 0
    },
    "data": {
      "label": "Detect the hook from the first words (single entry point)",
      "info": {
        "summary": "The single entry point of the spoken command mode: it extracts the first ~20 words of a message, uses a cheap model to determine whether the message contains one of the registered hooks from the global project_hooks table (step 187), and classifies the intent. Shared infrastructure — not just for notes.",
        "processes": [
          "read active hooks from project_hooks (187) + normalize.ts",
          "first ~20 words → cheap model → action/projectSlug or ignore",
          "payload = the tail after the phrase; empty → ignore",
          "compact classifier prompt (token efficiency)"
        ],
        "kind": "transform",
        "task": "Implement the hook detector. (1) Read the active hooks from the project_hooks table (187) via @/lib/db (normalized phrases + action save/remind/recall + the owning projectSlug). (2) For each message: take the first ~20 words and run them through a cheap model via OPENAI_API_KEY with a classifier prompt \"does the text contain one of these hooks; return action and projectSlug or ignore\" (normalize case, ё/е, and extra whitespace via lib/hooks/normalize.ts from step 187). (3) payload = the text AFTER the hook phrase; empty payload → ignore. (4) Return an array of {intent: save|remind|recall|ignore, projectSlug, payload, chatId, messageId, date}. Messages without a hook → ignore and go no further. A cheap model with no heavy instructions — minimal cost (the token-efficiency thesis).",
        "tools": [
          "project_hooks (table, step 187) via @/lib/db",
          "lib/hooks/normalize.ts (187)",
          "cheap model via OPENAI_API_KEY",
          "fetch"
        ],
        "envKeys": [
          "OPENAI_API_KEY"
        ],
        "io": {
          "in": "array of messages {chatId, messageId, text, date}",
          "out": "array of classified {intent: save|remind|recall|ignore, projectSlug, payload, chatId, messageId, date}"
        }
      }
    }
  },
  {
    "id": "summarize-message",
    "type": "process",
    "position": {
      "x": 780,
      "y": 0
    },
    "data": {
      "label": "Detailed message summary (cheap model)",
      "info": {
        "summary": "For messages with intent=save and intent=remind it produces a detailed summary of the full text using a cheap model — for the memory record and the results table.",
        "processes": [
          "inline cheap-model call (no separate skill)",
          "input/output length caps (token thrift)",
          "on failure → summary = truncated original text (don't crash)"
        ],
        "kind": "action",
        "task": "Implement the inline summary. For each intent in {save, remind}: (1) POST to a cheap model via OPENAI_API_KEY (the same key as detect-hook; NOT a separate skill — an inline call) with the prompt \"produce a concise but complete summary of this message, preserving key facts and dates\". (2) Cap the input/output length (token thrift). (3) Return {messageId, summary} alongside the original fields. A summary failure must NOT crash the run: summary = the first N characters of the original text (graceful degradation).",
        "tools": [
          "cheap model via OPENAI_API_KEY",
          "fetch"
        ],
        "envKeys": [
          "OPENAI_API_KEY"
        ],
        "io": {
          "in": "classified messages intent in {save, remind} {payload, chatId, messageId, date}",
          "out": "the same + {summary} for each message"
        }
      }
    }
  },
  {
    "id": "search-memory-recall",
    "type": "process",
    "position": {
      "x": 780,
      "y": 100
    },
    "data": {
      "label": "Find an answer in the notes (LightRAG query)",
      "info": {
        "summary": "For intent=recall it runs a semantic search over vector memory (LightRAG hybrid) and builds the answer text straight from memory.",
        "processes": [
          "query mode=hybrid with X-Agent-Identity",
          "empty result → honest \"nothing found\"",
          "on failure → graceful degradation"
        ],
        "kind": "action",
        "task": "Implement the search. For each intent=recall: (1) POST /api/rag/query (LightRAG :9621) mode=hybrid, query=payload, header X-Agent-Identity: telegram-notes. (2) The LightRAG response is ready connected text (retrieval + generation on the memory side; the project does NOT call an LLM API directly — the \"subscription only / Hermes's place\" rule). (3) Empty result → an honest \"nothing found in your notes for the query: <payload>\". (4) On a query failure → gently \"memory is temporarily unavailable\". Return {chatId, answer}.",
        "tools": [
          "LightRAG /api/rag/query mode=hybrid (:9621)",
          "fetch with X-Agent-Identity"
        ],
        "envKeys": [],
        "io": {
          "in": "messages intent=recall {payload, chatId}",
          "out": "answers {chatId, answer, error?}"
        }
      }
    }
  },
  {
    "id": "persist-note-to-db",
    "type": "process",
    "position": {
      "x": 1040,
      "y": 0
    },
    "data": {
      "label": "Write the note/reminder to the project DB",
      "info": {
        "summary": "Writes a row to the project's own table: project name, hook, chat, date, date-reminder data (only for remind — type 1), full original text, summary, and an auto id.",
        "processes": [
          "telegram_notes table in SCHEMA (all columns from the owner's vision)",
          "save → reminder_due NULL; remind+date → reminder_due unix; remind without date → needs_when",
          "return dbId (for memory and the reply)"
        ],
        "kind": "action",
        "task": "Implement the DB write. (1) Declare in SCHEMA the table telegram_notes (id INTEGER PRIMARY KEY AUTOINCREMENT, project_slug TEXT, hook_action TEXT, chat_id TEXT, msg_date INTEGER, reminder_due INTEGER NULL, full_text TEXT, summary TEXT, created_at INTEGER). (2) For intent=save: reminder_due=NULL (a note, type 2). (3) For intent=remind: extract the date/time from payload with the cheap model (or from detect-hook); if there is no date, mark needs_when=true (the reply node will ask \"when?\") and do not create a row with reminder_due yet; if there is a date, reminder_due = unix time (type 1, date push). (4) Return {dbId, intent, reminder_due, needs_when, chatId, summary} — dbId is needed for memory and the reply. New tables ONLY in SCHEMA (they appear in both environments).",
        "tools": [
          "SQLite via @/lib/db (SCHEMA)",
          "cheap model via OPENAI_API_KEY (date parsing)"
        ],
        "envKeys": [
          "OPENAI_API_KEY"
        ],
        "io": {
          "in": "messages intent in {save, remind} with {summary, payload, chatId, date}",
          "out": "{dbId, intent, reminder_due, needs_when, chatId, summary} for each record"
        }
      }
    }
  },
  {
    "id": "ingest-note-to-memory",
    "type": "process",
    "position": {
      "x": 1300,
      "y": 0
    },
    "data": {
      "label": "Write the note to vector memory (LightRAG)",
      "info": {
        "summary": "Puts a formatted note into LightRAG — the workspace's shared vector memory (:9621) — so the record is unambiguously identifiable on search.",
        "processes": [
          "document format: project→hook→date→#dbId→text",
          "ingest with X-Agent-Identity: telegram-notes",
          "on failure → {ingestOk:false}, the run doesn't crash"
        ],
        "kind": "action",
        "task": "Implement the ingest into memory. For each DB record (intent in {save, remind}): (1) build a document in the format: \"Project: telegram-notes | Hook: <action> | Date: <YYYY-MM-DD HH:mm> | Record #<dbId> | <full text>\" (the DB id inside the text so the reply can reference the record). (2) POST /api/rag/ingest (LightRAG :9621 through the workspace API) with the header X-Agent-Identity: telegram-notes. (3) Short text is valid (confirmed in step 181). (4) An ingest failure must NOT crash the run: it is recorded in the result and passed to the user's reply.",
        "tools": [
          "LightRAG /api/rag/ingest (:9621)",
          "fetch with X-Agent-Identity"
        ],
        "envKeys": [],
        "io": {
          "in": "DB records {dbId, intent, chatId, summary} + full text",
          "out": "{dbId, chatId, ingestOk, error?} for each record"
        }
      }
    }
  },
  {
    "id": "reply-in-telegram",
    "type": "process",
    "position": {
      "x": 1560,
      "y": 0
    },
    "data": {
      "label": "Reply to the user in Telegram",
      "info": {
        "summary": "The final node: a save confirmation (\"Saved\"), a \"when?\" question for a remind without a date, or the found recall answer — back to the same chat via sendMessage.",
        "processes": [
          "save→confirmation, remind→\"I'll remind you\"/\"when?\", recall→answer",
          "plain text without parse_mode, cut at >4096",
          "run summary {processed,saved,reminded,answered,errors[]}"
        ],
        "kind": "action",
        "task": "Implement the reply. Assemble the outcomes: (1) save → \"Saved: <summary>\" when ingestOk, \"Couldn't save: <error>\" on failure. (2) remind with a date → \"I'll remind you <date>: <summary>\". (3) remind needs_when=true → \"When should I remind you? Reply with a date/time\" (the user's next message is processed as the date — simplified in the MVP: the user resends with a date). (4) recall → the answer from search-memory-recall. (5) POST sendMessage, do not set parse_mode (plain text — free-form input must not break on Markdown special characters); text > 4096 is cut on a paragraph boundary. (6) Run summary {processed, saved, reminded, answered, errors[]} — this is the result for the dashboard and the results table (Layer C).",
        "tools": [
          "Telegram Bot API sendMessage",
          "fetch"
        ],
        "envKeys": [
          "TELEGRAM_BOT_TOKEN"
        ],
        "io": {
          "in": "ingest results {dbId,chatId,ingestOk,summary}, needs_when, recall {chatId,answer}",
          "out": "run summary {processed, saved, reminded, answered, errors[]} for the dashboard/table"
        }
      }
    }
  }
];

export const FLOW_EDGES: Edge[] = [
  {
    "id": "e-telegram-cron-trigger-fetch-telegram-updates",
    "source": "telegram-cron-trigger",
    "target": "fetch-telegram-updates",
    "animated": true
  },
  {
    "id": "e-telegram-cron-trigger-deliver-due-reminders",
    "source": "telegram-cron-trigger",
    "target": "deliver-due-reminders",
    "animated": true
  },
  {
    "id": "e-fetch-telegram-updates-detect-hook",
    "source": "fetch-telegram-updates",
    "target": "detect-hook"
  },
  {
    "id": "e-detect-hook-summarize-message",
    "source": "detect-hook",
    "target": "summarize-message"
  },
  {
    "id": "e-detect-hook-search-memory-recall",
    "source": "detect-hook",
    "target": "search-memory-recall"
  },
  {
    "id": "e-summarize-message-persist-note-to-db",
    "source": "summarize-message",
    "target": "persist-note-to-db"
  },
  {
    "id": "e-persist-note-to-db-ingest-note-to-memory",
    "source": "persist-note-to-db",
    "target": "ingest-note-to-memory"
  },
  {
    "id": "e-ingest-note-to-memory-reply-in-telegram",
    "source": "ingest-note-to-memory",
    "target": "reply-in-telegram"
  },
  {
    "id": "e-search-memory-recall-reply-in-telegram",
    "source": "search-memory-recall",
    "target": "reply-in-telegram"
  }
];
