import type { Edge, Node } from "@xyflow/react";

// fractera:flow os-244071e59531649b — GENERATED by orchestrate-project-by-steps from the
// decomposition graph (step 184, contract R6). This diagram is the project's
// EXECUTION SCHEMA: what is not on it does not exist in the project. The file is
// DERIVED — a re-run rewrites it deterministically, so NEVER hand-edit it: to
// change the diagram, extend the graph and re-run the engine. Each node's `info`
// is the payload of the on-canvas info panel (R8).
export type FlowNodeInfo = {
  summary: string;
  processes: string[];
  kind: "trigger" | "action" | "transform";
  task?: string;
  tools: string[];
  envKeys: string[];
  io?: { in: unknown; out: unknown };
};

export type FlowNodeData = {
  label: string;
  info: FlowNodeInfo;
};

export type FlowNode = Node<FlowNodeData, "process">;

export const FLOW_NODES: FlowNode[] = [
  {
    "id": "telegram-cron-trigger",
    "type": "process",
    "position": {
      "x": 0,
      "y": 0
    },
    "data": {
      "label": "Cron-триггер: запуск конвейера раз в минуту",
      "info": {
        "summary": "Точка входа. Вместо Telegram-webhook (требует HTTPS, недоступен в IP-режиме и привязал бы к нативному шлюзу Hermes) используется поллинг: co-located cron.json планирует запуск run-роута каждую минуту через fractera-cron (субстрат-планировщик шага 179); тот же роут доступен вручную из run-панели страницы проекта.",
        "processes": [
          "cron.json с расписанием * * * * * рядом со страницей проекта",
          "run-роут: пустое тело от cron и {simulateMessage?} от run-панели",
          "роут возвращает runId, вся логика — в workflow-шагах"
        ],
        "kind": "trigger",
        "task": "Настроить триггер конвейера. (1) Создать co-located cron.json в app/(projects)/projects/personal/telegram-notes/ с расписанием «* * * * *» (каждую минуту), целью POST /api/projects/personal/telegram-notes/run, пустым телом — fractera-cron подхватывает co-located cron.json автоматически. (2) Run-роут (route.ts рядом с _workflow/definition.ts) принимает пустое тело от cron и опциональный ручной input из run-панели ({ simulateMessage?: string } — для теста без Telegram: строка обрабатывается как будто пришла из чата). (3) Роут стартует durable-прогон runProject (WDK, world-local, шаг 183) и возвращает runId; никакой бизнес-логики в роуте.",
        "tools": [
          "fractera-cron (co-located cron.json)",
          "run route POST /api/projects/personal/telegram-notes/run",
          "Workflow DevKit (world-local)"
        ],
        "envKeys": [],
        "io": {
          "in": "cron-тик раз в минуту ИЛИ ручной запуск из run-панели (опц. simulateMessage)",
          "out": "запущенный durable-прогон runProject (runId)"
        }
      }
    }
  },
  {
    "id": "fetch-telegram-updates",
    "type": "process",
    "position": {
      "x": 260,
      "y": 0
    },
    "data": {
      "label": "Получить новые сообщения из Telegram (getUpdates)",
      "info": {
        "summary": "Опрашивает Telegram Bot API методом getUpdates с персистентным курсором last_update_id, отдаёт только новые сообщения владельца (личка с ботом @fractera_bot).",
        "processes": [
          "таблица telegram_notes_state в SCHEMA (key/value, курсор last_update_id)",
          "getUpdates с offset и фильтром по TELEGRAM_ALLOWED_CHAT_ID",
          "курсор продвигается до обработки (нет повторов при сбое)",
          "ветка simulateMessage для теста без Telegram"
        ],
        "kind": "action",
        "task": "Реализовать тело шага получения обновлений. (1) Объявить в SCHEMA (app/lib/db/index.ts — новые таблицы ТОЛЬКО в SCHEMA) таблицу telegram_notes_state (key TEXT PRIMARY KEY, value TEXT) для курсора last_update_id. (2) GET https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getUpdates?offset=<last_update_id+1>&timeout=0 — короткий запрос без long-poll (шаг живёт внутри минутного тика). (3) Отфильтровать: только message с текстом; если задан TELEGRAM_ALLOWED_CHAT_ID — отбросить чужие чаты. (4) Продвинуть курсор на максимальный update_id СРАЗУ после чтения (защита от повторной обработки при падении дальше). (5) Вернуть массив {chatId, messageId, text, date}. (6) Если пришёл simulateMessage из run-панели — вернуть его как единственное сообщение с chatId = TELEGRAM_ALLOWED_CHAT_ID, Telegram не опрашивать. Токен НИКОГДА не хардкодить — только env (уже в слот-.env.local, правило 143).",
        "tools": [
          "Telegram Bot API getUpdates",
          "SQLite через @/lib/db (SCHEMA)",
          "fetch"
        ],
        "envKeys": [
          "TELEGRAM_BOT_TOKEN",
          "TELEGRAM_ALLOWED_CHAT_ID"
        ],
        "io": {
          "in": "cron-тик (пусто) или simulateMessage из run-панели",
          "out": "массив новых сообщений {chatId, messageId, text, date}; курсор last_update_id продвинут"
        }
      }
    }
  },
  {
    "id": "deliver-due-reminders",
    "type": "process",
    "position": {
      "x": 260,
      "y": 100
    },
    "data": {
      "label": "Доставить наступившие напоминания (дата-пуш)",
      "info": {
        "summary": "Единственное активное действие напоминаний (тип 1): на каждом cron-тике проверяет БД на наступившие reminder_due и шлёт пользователю текст напоминания в Telegram.",
        "processes": [
          "SELECT наступивших reminder_due (не delivered)",
          "sendMessage дословным текстом напоминания",
          "пометить delivered; колонка delivered в SCHEMA"
        ],
        "kind": "action",
        "task": "Реализовать доставку напоминаний. (1) SELECT из telegram_notes, где reminder_due <= now И не помечено delivered. (2) Для каждой: POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage в chat_id с текстом «Напоминание: вы просили напомнить, что в <HH:mm> нужно <payload/summary>» (дословно то, что заложил пользователь — правильное поведение из видения владельца). (3) Пометить строку delivered=1 (добавить колонку в SCHEMA-таблицу). (4) Идёт параллельной веткой от триггера — не зависит от прихода новых сообщений. Сбой отправки логировать, не ретраить внутри тика (следующий тик повторит).",
        "tools": [
          "Telegram Bot API sendMessage",
          "SQLite через @/lib/db",
          "fetch"
        ],
        "envKeys": [
          "TELEGRAM_BOT_TOKEN"
        ],
        "io": {
          "in": "cron-тик (проверка due на каждом прогоне)",
          "out": "{delivered: n, errors[]} — отправленные напоминания"
        }
      }
    }
  },
  {
    "id": "detect-hook",
    "type": "process",
    "position": {
      "x": 520,
      "y": 0
    },
    "data": {
      "label": "Распознать хук по первым словам (единая точка входа)",
      "info": {
        "summary": "Единая точка входа командного голосового режима: извлекает первые ~20 слов сообщения, дешёвой моделью определяет, содержит ли сообщение один из зарегистрированных хуков глобальной таблицы project_hooks (шаг 187), и классифицирует намерение. Общая инфраструктура — не только для заметок.",
        "processes": [
          "чтение активных хуков из project_hooks (187) + normalize.ts",
          "первые ~20 слов → дешёвая модель → action/projectSlug или ignore",
          "payload = хвост после фразы; пустой → ignore",
          "промпт-классификатор компактный (токен-эффективность)"
        ],
        "kind": "transform",
        "task": "Реализовать распознаватель хука. (1) Прочитать активные хуки из таблицы project_hooks (187) через @/lib/db (нормализованные фразы + action save/remind/recall + projectSlug-владелец). (2) Для каждого сообщения: взять первые ~20 слов, прогнать через дешёвую модель по OPENAI_API_KEY с промптом-классификатором «содержит ли текст один из этих хуков; верни action и projectSlug или ignore» (нормализация регистра, ё/е, лишних пробелов через lib/hooks/normalize.ts шага 187). (3) payload = текст ПОСЛЕ фразы-хука; пустой payload → ignore. (4) Вернуть массив {intent: save|remind|recall|ignore, projectSlug, payload, chatId, messageId, date}. Сообщения без хука → ignore, дальше не идут. Дешёвая модель без тяжёлых инструкций — минимальный расход (тезис токен-эффективности).",
        "tools": [
          "project_hooks (таблица 187) через @/lib/db",
          "lib/hooks/normalize.ts (187)",
          "дешёвая модель по OPENAI_API_KEY",
          "fetch"
        ],
        "envKeys": [
          "OPENAI_API_KEY"
        ],
        "io": {
          "in": "массив сообщений {chatId, messageId, text, date}",
          "out": "массив классифицированных {intent: save|remind|recall|ignore, projectSlug, payload, chatId, messageId, date}"
        }
      }
    }
  },
  {
    "id": "summarize-message",
    "type": "process",
    "position": {
      "x": 780,
      "y": 0
    },
    "data": {
      "label": "Подробное summary сообщения (дешёвая модель)",
      "info": {
        "summary": "Для сообщений intent=save и intent=remind делает подробное summary полного текста дешёвой моделью — для записи в память и в таблицу результатов.",
        "processes": [
          "инлайн-вызов дешёвой модели (без отдельного навыка)",
          "лимиты длины вход/выход (токен-экономия)",
          "сбой → summary = усечённый исходный текст (не падать)"
        ],
        "kind": "action",
        "task": "Реализовать инлайн-summary. Для каждого intent∈{save,remind}: (1) POST к дешёвой модели по OPENAI_API_KEY (тот же ключ, что detect-hook; НЕ отдельный навык — инлайн-вызов) с промптом «сделай сжатое, но полное summary этого сообщения, сохрани ключевые факты и даты». (2) Ограничить длину входа/выхода (токен-экономия). (3) Вернуть {messageId, summary} рядом с исходными полями. Сбой summary НЕ роняет прогон: summary = первые N символов исходного текста (мягкая деградация).",
        "tools": [
          "дешёвая модель по OPENAI_API_KEY",
          "fetch"
        ],
        "envKeys": [
          "OPENAI_API_KEY"
        ],
        "io": {
          "in": "классифицированные сообщения intent∈{save,remind} {payload, chatId, messageId, date}",
          "out": "те же + {summary} на каждое сообщение"
        }
      }
    }
  },
  {
    "id": "search-memory-recall",
    "type": "process",
    "position": {
      "x": 780,
      "y": 100
    },
    "data": {
      "label": "Найти ответ по заметкам (LightRAG query)",
      "info": {
        "summary": "Для intent=recall выполняет семантический поиск по векторной памяти (LightRAG hybrid) и формирует текст ответа прямо из памяти.",
        "processes": [
          "query mode=hybrid c X-Agent-Identity",
          "пустой результат → честное «ничего не нашлось»",
          "сбой → мягкая деградация"
        ],
        "kind": "action",
        "task": "Реализовать поиск. Для каждого intent=recall: (1) POST /api/rag/query (LightRAG :9621) mode=hybrid, query=payload, заголовок X-Agent-Identity: telegram-notes. (2) Ответ LightRAG — готовый связный текст (retrieval+генерация на стороне памяти; прямой LLM-API из проекта НЕ вызывается — правило «только подписка/место Гермеса»). (3) Пустой результат → честный «по вашим заметкам ничего не нашлось по запросу: <payload>». (4) Сбой query → мягко «память временно недоступна». Вернуть {chatId, answer}.",
        "tools": [
          "LightRAG /api/rag/query mode=hybrid (:9621)",
          "fetch с X-Agent-Identity"
        ],
        "envKeys": [],
        "io": {
          "in": "сообщения intent=recall {payload, chatId}",
          "out": "ответы {chatId, answer, error?}"
        }
      }
    }
  },
  {
    "id": "persist-note-to-db",
    "type": "process",
    "position": {
      "x": 1040,
      "y": 0
    },
    "data": {
      "label": "Записать заметку/напоминание в БД проекта",
      "info": {
        "summary": "Пишет строку в собственную таблицу проекта: имя проекта, хук, чат, дата, данные напоминания по дате (только для remind — тип 1), полный исходный текст, summary, авто-идентификатор.",
        "processes": [
          "таблица telegram_notes в SCHEMA (все колонки видения владельца)",
          "save → reminder_due NULL; remind+дата → reminder_due unix; remind без даты → needs_when",
          "вернуть dbId (для памяти и ответа)"
        ],
        "kind": "action",
        "task": "Реализовать запись в БД. (1) Объявить в SCHEMA таблицу telegram_notes (id INTEGER PRIMARY KEY AUTOINCREMENT, project_slug TEXT, hook_action TEXT, chat_id TEXT, msg_date INTEGER, reminder_due INTEGER NULL, full_text TEXT, summary TEXT, created_at INTEGER). (2) Для intent=save: reminder_due=NULL (заметка, тип 2). (3) Для intent=remind: извлечь дату/время из payload дешёвой моделью (или из detect-hook); если даты нет — пометить needs_when=true (узел reply попросит «когда?»), строку с reminder_due не создавать пока; если дата есть — reminder_due = unix-время (тип 1, дата-пуш). (4) Вернуть {dbId, intent, reminder_due, needs_when, chatId, summary} — dbId нужен для памяти и ответа. Новые таблицы ТОЛЬКО в SCHEMA (появятся в обеих средах).",
        "tools": [
          "SQLite через @/lib/db (SCHEMA)",
          "дешёвая модель по OPENAI_API_KEY (разбор даты)"
        ],
        "envKeys": [
          "OPENAI_API_KEY"
        ],
        "io": {
          "in": "сообщения intent∈{save,remind} с {summary, payload, chatId, date}",
          "out": "{dbId, intent, reminder_due, needs_when, chatId, summary} на каждую запись"
        }
      }
    }
  },
  {
    "id": "ingest-note-to-memory",
    "type": "process",
    "position": {
      "x": 1300,
      "y": 0
    },
    "data": {
      "label": "Записать заметку в векторную память (LightRAG)",
      "info": {
        "summary": "Кладёт форматированную заметку в LightRAG — общую векторную память рабочего пространства (:9621) — так, чтобы при поиске запись однозначно идентифицировалась.",
        "processes": [
          "формат документа: проект→хук→дата→#dbId→текст",
          "ingest с X-Agent-Identity: telegram-notes",
          "сбой → {ingestOk:false}, прогон не падает"
        ],
        "kind": "action",
        "task": "Реализовать ingest в память. Для каждой записи из БД (intent∈{save,remind}): (1) сформировать документ форматом: «Проект: telegram-notes | Хук: <action> | Дата: <YYYY-MM-DD HH:mm> | Запись #<dbId> | <полный текст>» (идентификатор БД внутри текста — чтобы ответ мог сослаться на запись). (2) POST /api/rag/ingest (LightRAG :9621 через API рабочего пространства) с заголовком X-Agent-Identity: telegram-notes. (3) Короткий текст — валиден (подтверждено шагом 181). (4) Сбой ingest НЕ роняет прогон: фиксируется в результат, уходит в ответ пользователю.",
        "tools": [
          "LightRAG /api/rag/ingest (:9621)",
          "fetch с X-Agent-Identity"
        ],
        "envKeys": [],
        "io": {
          "in": "записи БД {dbId, intent, chatId, summary} + полный текст",
          "out": "{dbId, chatId, ingestOk, error?} на каждую запись"
        }
      }
    }
  },
  {
    "id": "reply-in-telegram",
    "type": "process",
    "position": {
      "x": 1560,
      "y": 0
    },
    "data": {
      "label": "Ответить пользователю в Telegram",
      "info": {
        "summary": "Финальный узел: подтверждение сохранения («Запомнил»), вопрос «когда?» для remind без даты, или найденный ответ recall — обратно в тот же чат методом sendMessage.",
        "processes": [
          "save→подтверждение, remind→«напомню»/«когда?», recall→answer",
          "plain text без parse_mode, резка >4096",
          "итог прогона {processed,saved,reminded,answered,errors[]}"
        ],
        "kind": "action",
        "task": "Реализовать ответ. Собрать исходы: (1) save → «Запомнил: <summary>» при ingestOk, «Не смог сохранить: <error>» при сбое. (2) remind с датой → «Напомню <дата>: <summary>». (3) remind needs_when=true → «Когда напомнить? Ответьте датой/временем» (следующее сообщение пользователя обработается как дата — упрощённо в MVP: пользователь повторит с датой). (4) recall → answer из search-memory-recall. (5) POST sendMessage, parse_mode не задавать (plain text — свободная форма не должна ломаться на Markdown-спецсимволах); текст >4096 резать по границе абзаца. (6) Итог прогона {processed, saved, reminded, answered, errors[]} — это результат для dashboard и таблицы результатов (Layer C).",
        "tools": [
          "Telegram Bot API sendMessage",
          "fetch"
        ],
        "envKeys": [
          "TELEGRAM_BOT_TOKEN"
        ],
        "io": {
          "in": "результаты ingest {dbId,chatId,ingestOk,summary}, needs_when, recall {chatId,answer}",
          "out": "итог прогона {processed, saved, reminded, answered, errors[]} для dashboard/таблицы"
        }
      }
    }
  }
];

export const FLOW_EDGES: Edge[] = [
  {
    "id": "e-telegram-cron-trigger-fetch-telegram-updates",
    "source": "telegram-cron-trigger",
    "target": "fetch-telegram-updates",
    "animated": true
  },
  {
    "id": "e-telegram-cron-trigger-deliver-due-reminders",
    "source": "telegram-cron-trigger",
    "target": "deliver-due-reminders",
    "animated": true
  },
  {
    "id": "e-fetch-telegram-updates-detect-hook",
    "source": "fetch-telegram-updates",
    "target": "detect-hook"
  },
  {
    "id": "e-detect-hook-summarize-message",
    "source": "detect-hook",
    "target": "summarize-message"
  },
  {
    "id": "e-detect-hook-search-memory-recall",
    "source": "detect-hook",
    "target": "search-memory-recall"
  },
  {
    "id": "e-summarize-message-persist-note-to-db",
    "source": "summarize-message",
    "target": "persist-note-to-db"
  },
  {
    "id": "e-persist-note-to-db-ingest-note-to-memory",
    "source": "persist-note-to-db",
    "target": "ingest-note-to-memory"
  },
  {
    "id": "e-ingest-note-to-memory-reply-in-telegram",
    "source": "ingest-note-to-memory",
    "target": "reply-in-telegram"
  },
  {
    "id": "e-search-memory-recall-reply-in-telegram",
    "source": "search-memory-recall",
    "target": "reply-in-telegram"
  }
];
